// 10과: 보배경 (Ratana Sutta, Snp 2.1) — text/제10과. 보배경.txt 전문, 첫 단어부터 모든 단어 학습
import type { StepType } from './lesson-data-sn56-11'

// 1-2 게송: 천신 초청
const V0A = 'Yānīdha bhūtāni samāgatāni, bhummāni vā yāni va antalikkhe.\nSabbeva bhūtā sumanā bhavantu, athopi sakkacca suṇantu bhāsitaṃ.'
const V0AK = '여기 모인 존재들이여, 지상에 있든 허공에 있든. 모든 존재가 기쁜 마음이 되기를, 그리고 주의 깊게 이 말씀을 들으라.'

const V0B = 'Tasmā hi bhūtā nisāmetha sabbe, mettaṃ karotha mānusiyā pajāya.\nDivā ca ratto ca haranti ye baliṃ, tasmā hi ne rakkhatha appamattā.'
const V0BK = '그러므로 모든 존재들이여 귀를 기울이라, 인간 무리에 자애를 행하라. 낮과 밤으로 공물을 바치는 자들을 방심 없이 보호하라.'

// 3 게송: 붓다 보배 1 (yaṃ 시작)
const V1 = 'Yaṃ kiñci vittaṃ idha vā huraṃ vā, saggesu vā yaṃ ratanaṃ paṇītaṃ.\nNa no samaṃ atthi tathāgatena, idampi buddhe ratanaṃ paṇītaṃ.\nEtena saccena suvatthi hotu.'
const V1K = '이 세상이든 저 세상이든 어떤 보물이든, 천상의 어떤 뛰어난 보배든 — 여래와 같은 것은 없다. 이것이 붓다 안의 뛰어난 보배. 이 진실에 의해 행복이 있기를.'

// 4 게송: 담마 보배 (멸·이탐·불사)
const V2 = 'Khayaṃ virāgaṃ amataṃ paṇītaṃ, yadajjhagā sakyamunī samāhito.\nNa tena dhammena samatthi kiñci, idampi dhamme ratanaṃ paṇītaṃ.\nEtena saccena suvatthi hotu.'
const V2K = '석가모니께서 삼매 속에서 도달하신 소멸·이탐·불사·뛰어남 — 그 담마와 같은 것은 없다. 이것이 담마 안의 뛰어난 보배.'

// 5 게송: 담마 보배 (즉시삼매)
const V3 = 'Yaṃ buddhaseṭṭho parivaṇṇayī suciṃ, samādhimānantarikaññamāhu.\nSamādhinā tena samo na vijjati, idampi dhamme ratanaṃ paṇītaṃ.\nEtena saccena suvatthi hotu.'
const V3K = '붓다 가운데 최고이신 분께서 칭찬하신 청정한 [삼매], 즉시 결과를 내는 삼매라 일컬어진 것 — 그와 같은 삼매는 없다. 이것이 담마 안의 뛰어난 보배.'

// 6 게송: 상가 보배 (4쌍 8배)
const V4 = 'Ye puggalā aṭṭha sataṃ pasatthā, cattāri etāni yugāni honti.\nTe dakkhiṇeyyā sugatassa sāvakā, etesu dinnāni mahapphalāni.\nIdampi saṅghe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V4K = '선한 자들에 의해 칭송받는 여덟 분의 사람들 — 이들은 네 쌍을 이룬다. 선서(善逝)의 제자인 그들은 보시받을 만하며, 그들에게 보시한 것은 큰 결실. 이것이 상가 안의 뛰어난 보배.'

// 7 게송: 상가 보배 (열반 누림)
const V5 = 'Ye suppayuttā manasā daḷhena, nikkāmino gotamasāsanamhi.\nTe pattipattā amataṃ vigayha, laddhā mudhā nibbutiṃ bhuñjamānā.\nIdampi saṅghe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V5K = '굳건한 마음으로 잘 정진하고 고따마의 가르침에서 욕망을 떠난 자들 — 그들은 얻을 것을 얻어 불사에 들어가, 값없이 얻은 적멸을 누리고 있다. 이것이 상가 안의 뛰어난 보배.'

// 8 게송: 상가 보배 (인드라 기둥 비유)
const V6 = 'Yathindakhīlo pathavissito siyā, catubbhi vātehi asampakampiyo.\nTathūpamaṃ sappurisaṃ vadāmi, yo ariyasaccāni avecca passati.\nIdampi saṅghe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V6K = '인드라 기둥이 땅에 박혀 사방의 바람에 흔들리지 않듯, 그와 같이 성스러운 진리를 꿰뚫어 보는 선인을 나는 말한다. 이것이 상가 안의 뛰어난 보배.'

// 9 게송: 상가 보배 (8생 안 옴)
const V7 = 'Ye ariyasaccāni vibhāvayanti, gambhīrapaññena sudesitāni.\nKiñcāpi te honti bhusaṃ pamattā, na te bhavaṃ aṭṭhamamādiyanti.\nIdampi saṅghe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V7K = '심오한 지혜로 잘 설해진 성스러운 진리들을 꿰뚫는 자들 — 비록 크게 방일하더라도, 여덟 번째 생을 받지 않는다. 이것이 상가 안의 뛰어난 보배.'

// 10 게송: 상가 보배 (3결 + 4악도)
const V8 = 'Sahāvassa dassanasampadāya, tayassu dhammā jahitā bhavanti.\nSakkāyadiṭṭhi vicikicchitañca, sīlabbataṃ vāpi yadatthi kiñci.\nCatūhapāyehi ca vippamutto, chaccābhiṭhānāni abhabba kātuṃ.\nIdampi saṅghe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V8K = '그(예류자)에게 봄의 성취와 동시에 세 법이 버려진다 — 유신견·의심·계금취. 4악도에서 벗어나고, 여섯 가지 큰 죄를 지을 수 없다. 이것이 상가 안의 뛰어난 보배.'

// 11 게송: 상가 보배 (예류자 죄 못 감춤)
const V9 = 'Kiñcāpi so kamma karoti pāpakaṃ, kāyena vācā uda cetasā vā.\nAbhabba so tassa paṭicchadāya, abhabbatā diṭṭhapadassa vuttā.\nIdampi saṅghe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V9K = '비록 그가 몸·말·뜻으로 어떤 악업을 짓더라도, 그것을 감출 수 없다. 길을 본 자에게는 (감춤이) 불가능하다고 일컬어진다. 이것이 상가 안의 뛰어난 보배.'

// 12 게송: 붓다 보배 (꽃핀 숲)
const V10 = 'Vanappagumbe yatha phussitagge, gimhānamāse paṭhamasmiṃ gimhe.\nTathūpamaṃ dhammavaraṃ adesayi, nibbānagāmiṃ paramaṃ hitāya.\nIdampi buddhe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V10K = '여름 첫 달 꼭대기까지 꽃핀 숲처럼, 그와 같이 뛰어난 담마를 설하셨다 — 열반으로 이끄는 최상의 이익을 위해. 이것이 붓다 안의 뛰어난 보배.'

// 13 게송: 붓다 보배 (4중 vara)
const V11 = 'Varo varaññū varado varāharo, anuttaro dhammavaraṃ adesayi.\nIdampi buddhe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V11K = '최고이시고 최고를 아시고 최고를 주시고 최고를 가져오신 분 — 무상하신 분께서 뛰어난 담마를 설하셨다. 이것이 붓다 안의 뛰어난 보배.'

// 14 게송: 상가 보배 (등불 비유)
const V12 = 'Khīṇaṃ purāṇaṃ nava natthi sambhavaṃ, virattacittāyatike bhavasmiṃ.\nTe khīṇabījā avirūḷhichandā, nibbanti dhīrā yathāyaṃ padīpo.\nIdampi saṅghe ratanaṃ paṇītaṃ, etena saccena suvatthi hotu.'
const V12K = '옛 (업)은 다하고 새 발생은 없다, 미래 존재에 탐욕을 떠난 마음. 종자가 다하고 자라남의 의욕이 없어, 등불처럼 지혜로운 자들이 꺼진다. 이것이 상가 안의 뛰어난 보배.'

// 15-17 결어 (3보 예배)
const V13 = 'Yānīdha bhūtāni samāgatāni, bhummāni vā yāni va antalikkhe.\nTathāgataṃ devamanussapūjitaṃ, buddhaṃ namassāma suvatthi hotu.'
const V13K = '여기 모인 존재들이여, 지상에 있든 허공에 있든. 신과 인간이 공양하는 여래, 붓다께 예배. 행복이 있기를.'

const V14 = 'Yānīdha bhūtāni samāgatāni, bhummāni vā yāni va antalikkhe.\nTathāgataṃ devamanussapūjitaṃ, dhammaṃ namassāma suvatthi hotu.'
const V14K = '여기 모인 존재들이여... 신과 인간이 공양하는 여래의 담마께 예배. 행복이 있기를.'

const V15 = 'Yānīdha bhūtāni samāgatāni, bhummāni vā yāni va antalikkhe.\nTathāgataṃ devamanussapūjitaṃ, saṅghaṃ namassāma suvatthi hotūti.'
const V15K = '여기 모인 존재들이여... 신과 인간이 공양하는 여래의 상가께 예배. 행복이 있기를.'

export const LESSON_RATANA: StepType[] = [
  { type: 'intro', icon: '💎', title: '보배경 (Ratana Sutta)', subtitle: 'Snp 2.1 — 삼보의 보배',
    description: '베살리 기근·역병·악귀 때 부처님께서 아난다에게 이 경을 가르쳐 도시 돌며 외우게 하여 재난을 사라지게 한 경.\n\n구조 (17 게송):\n• 1-2: 천신·존재들 초청\n• 3-13: 삼보 각각의 보배 + 후렴 "etena saccena suvatthi hotu"\n• 14-17: 결어 (3보 예배)\n\n첫 단어부터 모든 단어 학습.' },

  // ===== V0A 단어 — 첫 게송 첫 단어부터 =====
  { type: 'intro', icon: '🌟', title: '— 1게송: 천신 초청 (V0A) —', subtitle: '첫 단어부터 시작',
    description: '모든 단어 학습. yāni-idha → bhāsitaṃ까지.' },

  { type: 'teach', icon: '🔗', word: 'Yānīdha', pronKo: '야~니~다', meaning: '여기 ~한 것들 (관계대명사 복수 + 처격부사)',
    grammar: '관계대명사 + 처격부사 (산디)', baseForm: 'yāni(어떤 것들이) + idha(여기)',
    formNote: 'yāni + idha → yānīdha (모음 연결 산디)\n경의 첫 단어. "여기 [모인] 어떤 존재들이든"',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '🔁', word: 'yāni', pronKo: '야~니', meaning: '어떤 ~것들이 (관계대명사 주격 중성 복수)',
    grammar: '관계대명사, 주격 중성 복수', baseForm: 'ya- (관계대명사)',
    formNote: 'ya → yāni: 주격 중성 복수\n남성 ye / 여성 yā / 중성 yāni',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '📍', word: 'idha', pronKo: '이다', meaning: '여기서, 이 자리에',
    grammar: '부사 (장소)', baseForm: 'idha',
    formNote: '11과 MN10 V3·V_ANA1의 idha와 동일\n"여기, 이 가르침/이 세상에서"',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '👻', word: 'bhūtāni', pronKo: '부~따~니', meaning: '존재들 (주격 중성 복수)',
    grammar: '중성명사, 주격 복수', baseForm: 'bhūta (√bhū 있다)',
    formNote: '√bhū 과거분사 → "있는 것 = 존재/신령"\nbhūtāni = 주격/대격 복수',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '👥', word: 'samāgatāni', pronKo: '사마~가따~니', meaning: '모여든 (과거분사 주격 중성 복수)',
    grammar: '과거분사, 주격 중성 복수', baseForm: 'samāgata (saṃ + ā + √gam)',
    formNote: 'saṃ(함께) + ā + √gam(오다) → "함께 온 = 모인"',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '🌍', word: 'bhummāni', pronKo: '붐마~니', meaning: '지상의 (것들) (형용사 주격 중성 복수)',
    grammar: '형용사, 주격 중성 복수', baseForm: 'bhumma (지상의)',
    formNote: 'bhūmi(땅) + ma → bhumma\nbhūtāni 수식',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '✌️', word: 'vā', pronKo: '와~', meaning: '또는, 혹은',
    grammar: '접속사 (선택)', baseForm: 'vā',
    formNote: '"X vā Y vā" = "X든 Y든"\n게송 안에서 va(단축형)와 혼용',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '✌️', word: 'va', pronKo: '와', meaning: 'vā의 단축형 (운율 맞춤)',
    grammar: '접속사 (단축)', baseForm: 'vā → va',
    formNote: '시행 운율 위해 단축. 의미는 vā와 동일',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '☁️', word: 'antalikkhe', pronKo: '안딸릭케', meaning: '허공에 (처격 단수)',
    grammar: '중성명사, 처격 단수', baseForm: 'antalikkha (허공)',
    formNote: 'antalikkha → antalikkhe: 중성 -a 어간 처격 -e\n"중간 공간" = 지상과 천상 사이',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '🌟', word: 'Sabbeva', pronKo: '삽베와', meaning: '모두 다 (강조)',
    grammar: '형용사 주격 복수 + eva 강조', baseForm: 'sabbe + eva',
    formNote: 'sabbe(모든 자들이) + eva(바로/강조) = "모두 다 빠짐없이"',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '🌍', word: 'bhūtā', pronKo: '부~따~', meaning: '존재들이 (주격 남성 복수)',
    grammar: '남성명사, 주격 복수', baseForm: 'bhūta',
    formNote: 'bhūtāni(중성 복수)와 비교: bhūtā = 남성 복수',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '😄', word: 'sumanā', pronKo: '수마나~', meaning: '기쁜 마음의 (주격 복수)',
    grammar: '형용사, 주격 남성 복수', baseForm: 'sumana (su + mana)',
    formNote: 'su(잘) + mana(마음) = "기쁜 마음의"\n8과 metta의 sumanā와 동일',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '🙏', word: 'bhavantu', pronKo: '바완뚜', meaning: '되기를! (3복 명령)',
    grammar: '동사 3인칭 복수 명령형', baseForm: 'bhavati (있다, 되다)',
    formNote: '8과 metta의 bhavantu와 동일. 기원의 명령형',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '🔗', word: 'athopi', pronKo: '아토삐', meaning: '그리고 또한',
    grammar: '부사 + api', baseForm: 'atho + pi',
    formNote: 'atho(또한) + pi(도) → "그리고 또한"\n어조 강화',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '🎯', word: 'sakkacca', pronKo: '삭깟짜', meaning: '주의 깊게, 공경하여',
    grammar: '부사', baseForm: 'sakkacca',
    formNote: 'sakk(능력 있게) + acca → 공경의 부사',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '👂', word: 'suṇantu', pronKo: '수난뚜', meaning: '들으라! (3복 명령)',
    grammar: '동사 3인칭 복수 명령형', baseForm: 'suṇāti (듣다, √su)',
    formNote: '5과 sn45-8의 suṇātha(2복)와 같은 어근',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'teach', icon: '💬', word: 'bhāsitaṃ', pronKo: '바~시땅', meaning: '말씀을 (대격 단수)',
    grammar: '과거분사, 대격 중성 단수', baseForm: 'bhāsita (√bhās 말하다)',
    formNote: '11과 MN10 V_END4의 bhāsitaṃ과 동일',
    verseLine: V0A, verseLineKo: V0AK, audio: true },
  { type: 'verse', pali: V0A, pronKo: '야~니~다 부~따~니 사마~가따~니, 붐마~니 와~ 야~니 와 안딸릭케. 삽베와 부~따~ 수마나~ 바완뚜, 아토삐 삭깟짜 수난뚜 바~시땅.',
    translation: V0AK, highlight: ['Yānīdha','yāni','idha','bhūtāni','samāgatāni','bhummāni','vā','antalikkhe','Sabbeva','bhūtā','sumanā','bhavantu','athopi','sakkacca','suṇantu','bhāsitaṃ'],
    note: '🌟 천신 초청 — 모든 존재 환영.' },

  // ===== V0B 단어 =====
  { type: 'teach', icon: '⚖️', word: 'Tasmā', pronKo: '따스마~', meaning: '그러므로 (탈격, 부사적)',
    grammar: '대명사 탈격 (부사적)', baseForm: 'ta (그)',
    formNote: '"그것으로부터 = 그러므로"\n9과 sn22-59의 yasmā/tasmā와 같은 단어',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '❗', word: 'hi', pronKo: '히', meaning: '실로 (강조)',
    grammar: '불변사 (강조)', baseForm: 'hi',
    formNote: 'tasmā hi = "그러므로 실로"',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '👂', word: 'nisāmetha', pronKo: '니사~메타', meaning: '귀를 기울이라! (2복 명령)',
    grammar: '동사 2인칭 복수 명령', baseForm: 'nisāmeti',
    formNote: 'ni + √sām → "주의 깊게 듣다"',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '🌟', word: 'sabbe', pronKo: '삽베', meaning: '모든 (자들이여)',
    grammar: '형용사, 주격/호격 남성 복수', baseForm: 'sabba',
    formNote: 'Sabbeva의 sabbe + eva가 합쳐진 것 — 여기는 sabbe만',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '💛', word: 'mettaṃ', pronKo: '멧땅', meaning: '자애를 (대격)',
    grammar: '여성명사, 대격 단수', baseForm: 'mettā (자애)',
    formNote: '8과 metta의 mettā와 동일\nmettā → mettaṃ: -ā 어간 대격 -ṃ',
    buddhism: '자(慈). 4범주의 첫째.',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '🤝', word: 'karotha', pronKo: '까로타', meaning: '행하라! (2복 명령)',
    grammar: '동사 2인칭 복수 명령', baseForm: 'karoti (행하다, √kar)',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '👤', word: 'mānusiyā', pronKo: '마~누시야~', meaning: '인간의 (여격 여성)',
    grammar: '형용사, 여격 여성 단수', baseForm: 'mānusiya',
    formNote: 'manussa(인간) + iya → 형용사\n여격 -ā: "인간 무리에게"',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '👥', word: 'pajāya', pronKo: '빠자~야', meaning: '무리에게 (여격)',
    grammar: '여성명사, 여격 단수', baseForm: 'pajā (무리, 백성)',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '☀️', word: 'Divā', pronKo: '디와~', meaning: '낮에 (부사)',
    grammar: '부사', baseForm: 'divā',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '➕', word: 'ca', pronKo: '짜', meaning: '그리고 (접속사)',
    grammar: '불변사 (접속)', baseForm: 'ca',
    formNote: '"X ca Y ca" = "X와 Y"',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '🌙', word: 'ratto', pronKo: '랏또', meaning: '밤에 (부사)',
    grammar: '부사 (속격)', baseForm: 'ratti (밤)',
    formNote: 'ratti의 부사적 형태',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '🚚', word: 'haranti', pronKo: '하란띠', meaning: '가져온다, 바친다 (3복 현재)',
    grammar: '동사 3인칭 복수 현재', baseForm: 'harati (√har)',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '🔗', word: 'ye', pronKo: '예', meaning: '~한 자들이 (관계대명사 주격 남성 복수)',
    grammar: '관계대명사, 주격 남성 복수', baseForm: 'ya- (관계대명사)',
    formNote: 'yāni(중성)·yā(여성)·ye(남성) 비교',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '🎁', word: 'baliṃ', pronKo: '발링', meaning: '공물을 (대격)',
    grammar: '남성명사, 대격 단수', baseForm: 'bali',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '👉', word: 'ne', pronKo: '네', meaning: '그들을 (대격 복수)',
    grammar: '대명사, 대격 복수 (단축)', baseForm: 'taṃ → ne',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '🛡️', word: 'rakkhatha', pronKo: '락카타', meaning: '보호하라! (2복 명령)',
    grammar: '동사 2인칭 복수 명령', baseForm: 'rakkhati (보호하다)',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'teach', icon: '⚡', word: 'appamattā', pronKo: '압빠맛따~', meaning: '방심하지 않는 (자들로서)',
    grammar: '형용사, 주격 남성 복수', baseForm: 'a + pamatta (방일한)',
    formNote: '11과 MN10 V_NIV4 uddhaccakukkucca의 반대\n부처님 마지막 유훈 "appamādena sampādetha"',
    buddhism: '불방일(不放逸).',
    verseLine: V0B, verseLineKo: V0BK, audio: true },
  { type: 'verse', pali: V0B, pronKo: '따스마~ 히 부~따~ 니사~메타 삽베, 멧땅 까로타 마~누시야~ 빠자~야. 디와~ 짜 랏또 짜 하란띠 예 발링, 따스마~ 히 네 락카타 압빠맛따~.',
    translation: V0BK, highlight: ['Tasmā','hi','nisāmetha','sabbe','mettaṃ','karotha','mānusiyā','pajāya','Divā','ratto','haranti','baliṃ','ne','rakkhatha','appamattā'],
    note: '🛡️ 천신들에게 인간 보호 부탁.' },

  // ===== V1: Yaṃ kiñci... 시작 (사용자가 말한 yaṃ!) =====
  { type: 'intro', icon: '☸️', title: '— 3게송: 붓다 보배 1 (yaṃ 시작) —', subtitle: 'V1',
    description: '여래와 같은 보배는 없다.' },
  { type: 'teach', icon: '🔗', word: 'Yaṃ', pronKo: '양', meaning: '어떤 ~이든 (관계대명사 주격/대격 중성 단수)',
    grammar: '관계대명사, 주격/대격 중성 단수', baseForm: 'ya- (관계대명사)',
    formNote: '게송의 핵심 첫 단어! V1에서 "yaṃ kiñci" = "어떤 ~이든 무엇이든"\n9과 sn22-59 V7의 "yaṃ kiñci"와 동일 정형구',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '❓', word: 'kiñci', pronKo: '낀찌', meaning: '어떤 무엇이든',
    grammar: '부정대명사', baseForm: 'kiñ + ci',
    formNote: 'kiṃ(무엇) + ci(어떤) = "어떤 무엇이든"\n"Yaṃ kiñci" = "어떤 X든 무엇이든"',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '💰', word: 'vittaṃ', pronKo: '윗땅', meaning: '재물, 보물 (주격 중성)',
    grammar: '중성명사, 주격 단수', baseForm: 'vitta',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '🏠', word: 'idha vā huraṃ vā', pronKo: '이다 와~ 후랑 와~', meaning: '이 세상이든 저 세상이든',
    grammar: '부사 선택구문', baseForm: 'idha(여기) + huraṃ(저쪽)',
    formNote: 'idha = 이 세상 / huraṃ = 저 세상(피안)',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '☁️', word: 'saggesu', pronKo: '삭게수', meaning: '천상들에서 (처격 복수)',
    grammar: '남성명사, 처격 복수', baseForm: 'sagga (천상)',
    formNote: 'sagga → saggesu: -a 어간 처격 복수 -esu',
    buddhism: '6욕천 + 색계·무색계 = 31천.',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '💎', word: 'ratanaṃ', pronKo: '라따낭', meaning: '보배 (주격/대격 중성)',
    grammar: '중성명사, 주격/대격', baseForm: 'ratana',
    formNote: '경의 주제어',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '⭐', word: 'paṇītaṃ', pronKo: '빠니~땅', meaning: '뛰어난 (형용사)',
    grammar: '형용사, 주격 중성', baseForm: 'paṇīta',
    formNote: '9과 sn22-59 V7의 paṇītaṃ과 동일',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '🚫', word: 'Na', pronKo: '나', meaning: '~아니다 (부정)',
    grammar: '부정 불변사', baseForm: 'na',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '👥', word: 'no', pronKo: '노', meaning: '우리에게는 (속격 복수)',
    grammar: '대명사, 속격 복수', baseForm: 'ahaṃ',
    formNote: '"na no samaṃ" = "우리에게 같은 것은 없다"',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '⚖️', word: 'samaṃ', pronKo: '사망', meaning: '같은 (것이)',
    grammar: '형용사, 주격 중성', baseForm: 'sama',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '✅', word: 'atthi', pronKo: '앗티', meaning: '있다 (3단 현재)',
    grammar: '동사 3인칭 단수 현재', baseForm: 'atthi (√as)',
    formNote: '11과 MN10 REF_KAYA의 atthi와 동일',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '👼', word: 'tathāgatena', pronKo: '따타~가떼나', meaning: '여래에 의해 (도구격)',
    grammar: '남성명사, 도구격 단수', baseForm: 'tathāgata (tathā + gata)',
    formNote: 'tathā(그렇게) + gata(간) = "그렇게 간 분"\n11과 sn56-11 V4의 tathāgatena와 동일',
    buddhism: '여래(如來). 부처님 자칭.',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '👇', word: 'idampi', pronKo: '이담삐', meaning: '이것 또한',
    grammar: '대명사 + api', baseForm: 'idaṃ + pi',
    formNote: '후렴 시작 — "이것 또한 [삼보] 안의 보배"',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '☸️', word: 'buddhe', pronKo: '붓데', meaning: '붓다 안에 (처격)',
    grammar: '남성명사, 처격 단수', baseForm: 'buddha',
    formNote: 'buddha → buddhe: -a 어간 처격 -e',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '🔮', word: 'Etena', pronKo: '에떼나', meaning: '이 (도구격)',
    grammar: '지시대명사, 도구격', baseForm: 'eta',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '💡', word: 'saccena', pronKo: '삿쩨나', meaning: '진실에 의해 (도구격)',
    grammar: '중성명사, 도구격 단수', baseForm: 'sacca (진리)',
    formNote: 'etena saccena = "이 진실에 의해" — 진실서원(saccakiriyā) 정형구',
    buddhism: '진실(眞實). 삼보 공덕의 진실로 가피 기원.',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '✨', word: 'suvatthi', pronKo: '수왓티', meaning: '안녕, 행복',
    grammar: '여성명사, 주격', baseForm: 'su + atthi',
    formNote: 'su(잘) + atthi(있음) = "잘 있음 = 안녕"',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '🙏', word: 'hotu', pronKo: '호뚜', meaning: '있기를! (3단 명령)',
    grammar: '동사 3인칭 단수 명령', baseForm: 'bhavati',
    formNote: 'V0A의 bhavantu(복수) 단수형',
    verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'verse', pali: V1, pronKo: '양 낀찌 윗땅 이다 와~ 후랑 와~, 삭게수 와~ 양 라따낭 빠니~땅. 나 노 사망 앗티 따타~가떼나, 이담삐 붓데 라따낭 빠니~땅. 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V1K, highlight: ['Yaṃ','kiñci','vittaṃ','idha','huraṃ','saggesu','ratanaṃ','paṇītaṃ','samaṃ','atthi','tathāgatena','idampi','buddhe','Etena','saccena','suvatthi','hotu'],
    note: '☸️ 붓다 보배 — yaṃ으로 시작. 여래와 같은 것은 없다.' },

  // ===== V2: 담마 보배 (소멸·이탐·불사) =====
  { type: 'intro', icon: '📜', title: '— 4게송: 담마 보배 (V2) —', subtitle: '소멸·이탐·불사',
    description: '석가모니가 삼매 속에서 도달한 4법.' },
  { type: 'teach', icon: '🌬️', word: 'Khayaṃ', pronKo: '카양', meaning: '소멸 (대격)',
    grammar: '남성명사, 대격', baseForm: 'khaya',
    buddhism: '진(盡). 번뇌 소멸.',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '🌫️', word: 'virāgaṃ', pronKo: '위라~강', meaning: '이탐 (대격)',
    grammar: '남성명사, 대격', baseForm: 'virāga',
    formNote: '9과 sn22-59 V8의 virāgā와 같은 어근',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '🌌', word: 'amataṃ', pronKo: '아마땅', meaning: '불사 (대격)',
    grammar: '중성명사, 대격', baseForm: 'a + mata',
    formNote: 'a(부정) + mata(죽은) = "죽지 않는"',
    buddhism: '불사(不死). 열반의 별칭.',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '🏆', word: 'yadajjhagā', pronKo: '야다잣가~', meaning: '~을 도달하신',
    grammar: '관계대명사 + 동사 아오리스트', baseForm: 'yaṃ + ajjhagā',
    formNote: 'yaṃ(어떤 것을) + ajjhagā(도달했다) — 아오리스트',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '🙏', word: 'sakyamunī', pronKo: '사꺄무니~', meaning: '석가모니 (주격)',
    grammar: '남성명사, 주격', baseForm: 'sakya(석가족) + muni(성자)',
    buddhism: '석가족 성자 = 부처님.',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '🎯', word: 'samāhito', pronKo: '사마~히또', meaning: '삼매에 든 (과거분사 주격)',
    grammar: '과거분사, 주격 남성', baseForm: 'samāhita',
    formNote: '11과 MN10 V_CIT2의 samāhitaṃ과 어근 동일',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '⚖️', word: 'tena dhammena', pronKo: '떼나 담메나', meaning: '그 담마와 (도구격)',
    grammar: '대명사+명사 도구격', baseForm: 'ta + dhamma',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '⚖️', word: 'samatthi', pronKo: '사맛티', meaning: '같은 것 있다 (sama + atthi)',
    grammar: '복합', baseForm: 'samaṃ + atthi',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '📜', word: 'dhamme', pronKo: '담메', meaning: '담마 안에 (처격)',
    grammar: '남성명사, 처격', baseForm: 'dhamma',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'verse', pali: V2, pronKo: '카양 위라~강 아마땅 빠니~땅, 야다잣가~ 사꺄무니~ 사마~히또. 나 떼나 담메나 사맛티 낀찌, 이담삐 담메 라따낭 빠니~땅. 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V2K, highlight: ['Khayaṃ','virāgaṃ','amataṃ','yadajjhagā','sakyamunī','samāhito','dhamme'],
    note: '📜 담마 4법 = 멸·이탐·불사·뛰어남.' },

  // ===== V3: 담마 보배 (즉시삼매) =====
  { type: 'teach', icon: '🏔️', word: 'buddhaseṭṭho', pronKo: '붓다셋토', meaning: '붓다 중 최고 (주격)',
    grammar: '복합어, 주격', baseForm: 'buddha + seṭṭha (최고)',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '👏', word: 'parivaṇṇayī', pronKo: '빠리완나이~', meaning: '칭찬하셨다 (3단 아오리스트)',
    grammar: '동사 3인칭 단수 아오리스트', baseForm: 'parivaṇṇayati',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '✨', word: 'suciṃ', pronKo: '수찡', meaning: '청정한 (대격)',
    grammar: '형용사, 대격', baseForm: 'suci',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '⚡', word: 'samādhimānantarikaṃ', pronKo: '사마~디마~난따리깡', meaning: '즉시 결과를 내는 삼매 (대격)',
    grammar: '복합어, 대격', baseForm: 'samādhi + ānantarika (간격 없는)',
    buddhism: '무간정(無間定). 도(magga) 직후 즉시 과(phala) 일어남.',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '💬', word: 'āhu', pronKo: '아~후', meaning: '~라 일컬어진 (3복 완료)',
    grammar: '동사 3인칭 복수 완료', baseForm: 'āha (말하다)',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '🎯', word: 'samādhinā', pronKo: '사마~디나~', meaning: '삼매와 (도구격)',
    grammar: '남성명사, 도구격', baseForm: 'samādhi',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '⚖️', word: 'samo', pronKo: '사모', meaning: '같은 것이 (주격)',
    grammar: '형용사, 주격', baseForm: 'sama',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '🚫', word: 'na vijjati', pronKo: '나 윗자띠', meaning: '발견되지 않는다, 없다',
    grammar: '부정 + 동사 수동 3단', baseForm: 'na + vijjati',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'verse', pali: V3, pronKo: '양 붓다셋토 빠리완나이~ 수찡, 사마~디마~난따리깐냐마~후. 사마~디나~ 떼나 사모 나 윗자띠, 이담삐 담메 라따낭 빠니~땅. 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V3K, highlight: ['buddhaseṭṭho','parivaṇṇayī','suciṃ','samādhimānantarikaṃ','āhu','samādhinā','samo','vijjati'],
    note: '📜 담마 — 즉시삼매.' },

  // ===== V4: 상가 보배 (4쌍 8배) =====
  { type: 'intro', icon: '👥', title: '— 6게송: 상가 보배 (V4, 4쌍 8배) —', subtitle: '사향사과',
    description: '예류·일래·불환·아라한 각각 도+과 = 4쌍 8성.' },
  { type: 'teach', icon: '🔗', word: 'Ye', pronKo: '예', meaning: '~한 자들이 (관계대명사 주격 남성 복수)',
    grammar: '관계대명사, 주격 남성 복수', baseForm: 'ya-',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '👤', word: 'puggalā', pronKo: '뿍갈라~', meaning: '사람들이 (주격 복수)',
    grammar: '남성명사, 주격 복수', baseForm: 'puggala',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '8️⃣', word: 'aṭṭha', pronKo: '앗타', meaning: '여덟',
    grammar: '수사', baseForm: 'aṭṭha',
    formNote: '4과 tisarana-guna의 aṭṭha purisapuggalā와 동일',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🌟', word: 'sataṃ', pronKo: '사땅', meaning: '선한 자들에 의해 (속격 복수)',
    grammar: '대명사 속격 복수', baseForm: 'sat (선한 자)',
    formNote: '"선인들에 의해 칭송받는"',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '👏', word: 'pasatthā', pronKo: '빠삿타~', meaning: '칭송받는 (주격 복수)',
    grammar: '과거분사, 주격 복수', baseForm: 'pasattha',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '4️⃣', word: 'cattāri', pronKo: '짯따~리', meaning: '네 (중성 주격)',
    grammar: '수사 중성', baseForm: 'catur',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '👉', word: 'etāni', pronKo: '에따~니', meaning: '이것들이 (지시대명사 주격 중성 복수)',
    grammar: '지시대명사, 주격 중성 복수', baseForm: 'eta',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🔢', word: 'yugāni', pronKo: '유가~니', meaning: '쌍들 (주격 중성 복수)',
    grammar: '중성명사, 주격 복수', baseForm: 'yuga (쌍)',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '✅', word: 'honti', pronKo: '혼띠', meaning: '있다 (3복 현재)',
    grammar: '동사 3인칭 복수 현재', baseForm: 'bhavati',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '👉', word: 'Te', pronKo: '떼', meaning: '그들 (주격 남성 복수)',
    grammar: '대명사, 주격 남성 복수', baseForm: 'ta',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🎁', word: 'dakkhiṇeyyā', pronKo: '닥키네이야~', meaning: '보시받을 만한 (주격 복수)',
    grammar: '미래분사, 주격 복수', baseForm: 'dakkhiṇeyya',
    formNote: '4과 tisarana-guna의 dakkhiṇeyyo와 같은 어원',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🚢', word: 'sugatassa', pronKo: '수가땃사', meaning: '선서(善逝)의 (속격)',
    grammar: '남성명사, 속격', baseForm: 'sugata',
    formNote: '4과 tisarana-guna의 Sugato와 동일',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🎓', word: 'sāvakā', pronKo: '사~와까~', meaning: '제자들 (주격 복수)',
    grammar: '남성명사, 주격 복수', baseForm: 'sāvaka (√su 듣다)',
    formNote: '"들은 자 = 제자"',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '👉', word: 'etesu', pronKo: '에떼수', meaning: '그들에게 (처격 복수)',
    grammar: '지시대명사, 처격 남성 복수', baseForm: 'eta',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🎁', word: 'dinnāni', pronKo: '딘나~니', meaning: '주어진 것들 (과거분사 주격 중성 복수)',
    grammar: '과거분사, 주격 중성 복수', baseForm: 'dinna',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🌾', word: 'mahapphalāni', pronKo: '마합팔라~니', meaning: '큰 결실들 (주격 중성 복수)',
    grammar: '복합어, 주격 중성 복수', baseForm: 'mahā + phala',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🧘', word: 'saṅghe', pronKo: '상게', meaning: '상가 안에 (처격)',
    grammar: '남성명사, 처격', baseForm: 'saṅgha',
    verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'verse', pali: V4, pronKo: '예 뿍갈라~ 앗타 사땅 빠삿타~, 짯따~리 에따~니 유가~니 혼띠. 떼 닥키네이야~ 수가땃사 사~와까~, 에떼수 딘나~니 마합팔라~니. 이담삐 상게 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V4K, highlight: ['Ye','puggalā','aṭṭha','sataṃ','pasatthā','cattāri','yugāni','dakkhiṇeyyā','sugatassa','sāvakā','mahapphalāni','saṅghe'],
    note: '👥 상가 = 4쌍 8배의 성인.' },

  // ===== V5: 상가 보배 (열반 누림) =====
  { type: 'teach', icon: '💪', word: 'suppayuttā', pronKo: '숩빠윳따~', meaning: '잘 정진한 (주격 복수)',
    grammar: '과거분사, 주격 복수', baseForm: 'suppayutta',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '🧠', word: 'manasā', pronKo: '마나사~', meaning: '마음으로 (도구격)',
    grammar: '중성명사, 도구격', baseForm: 'mano',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '💪', word: 'daḷhena', pronKo: '달헤나', meaning: '굳건한 (도구격)',
    grammar: '형용사, 도구격', baseForm: 'daḷha',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '🆓', word: 'nikkāmino', pronKo: '닉까~미노', meaning: '욕망을 떠난 (주격 복수)',
    grammar: '형용사, 주격 복수', baseForm: 'nikkāmin',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '📖', word: 'gotamasāsanamhi', pronKo: '고따마사~사남히', meaning: '고따마 가르침에서 (처격)',
    grammar: '복합어, 처격', baseForm: 'gotama + sāsana',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '🎯', word: 'pattipattā', pronKo: '빳띱빳따~', meaning: '얻을 것을 얻은 (주격 복수)',
    grammar: '복합어', baseForm: 'patti + patta',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '🌌', word: 'vigayha', pronKo: '위가이하', meaning: '들어가서 (절대분사)',
    grammar: '절대분사', baseForm: 'vigāhati',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '✋', word: 'laddhā', pronKo: '랏다~', meaning: '얻어서 (절대분사)',
    grammar: '절대분사', baseForm: 'labhati',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '🎁', word: 'mudhā', pronKo: '무다~', meaning: '값없이',
    grammar: '부사', baseForm: 'mudhā',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '🕊️', word: 'nibbutiṃ', pronKo: '닙부띵', meaning: '적멸을 (대격)',
    grammar: '여성명사, 대격', baseForm: 'nibbuti',
    buddhism: '적멸. 열반의 다른 이름.',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '😌', word: 'bhuñjamānā', pronKo: '분자마~나~', meaning: '누리며 (현재분사 주격 복수)',
    grammar: '현재분사, 주격 복수', baseForm: 'bhuñjati (누리다)',
    verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'verse', pali: V5, pronKo: '예 숩빠윳따~ 마나사~ 달헤나, 닉까~미노 고따마사~사남히. 떼 빳띱빳따~ 아마땅 위가이하, 랏다~ 무다~ 닙부띵 분자마~나~. 이담삐 상게 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V5K, highlight: ['suppayuttā','manasā','daḷhena','nikkāmino','gotamasāsanamhi','pattipattā','vigayha','laddhā','mudhā','nibbutiṃ','bhuñjamānā'],
    note: '🕊️ 아라한들 열반 누림.' },

  // ===== V6: 인드라 기둥 =====
  { type: 'teach', icon: '🗿', word: 'Yathindakhīlo', pronKo: '야틴다키~로', meaning: '인드라 기둥처럼',
    grammar: '비교+복합어', baseForm: 'yathā + indakhīla',
    formNote: 'yathā(처럼) + indakhīla(석주)',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '🌍', word: 'pathavissito', pronKo: '빠타윗시또', meaning: '땅에 박힌 (과거분사 주격)',
    grammar: '복합어, 주격', baseForm: 'pathavi + sita (의지한)',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '✅', word: 'siyā', pronKo: '시야~', meaning: '~이라면 (가능법)',
    grammar: '동사 3단 가능법', baseForm: 'atthi 가능법',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '4️⃣', word: 'catubbhi', pronKo: '짜뚭비', meaning: '네 (도구격)',
    grammar: '수사, 도구격', baseForm: 'catur',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '🌬️', word: 'vātehi', pronKo: '와~떼히', meaning: '바람들에 의해 (도구격 복수)',
    grammar: '남성명사, 도구격 복수', baseForm: 'vāta',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '🗿', word: 'asampakampiyo', pronKo: '아삼빠깜삐요', meaning: '흔들리지 않는',
    grammar: '형용사, 주격', baseForm: 'a + sampakampiya',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '🟰', word: 'Tathūpamaṃ', pronKo: '따투~빠망', meaning: '그와 같이',
    grammar: '부사', baseForm: 'tathā + upama',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '🌳', word: 'sappurisaṃ', pronKo: '삽뿌리상', meaning: '선인을 (대격)',
    grammar: '복합어, 대격', baseForm: 'sat + purisa',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '🗣️', word: 'vadāmi', pronKo: '와다~미', meaning: '나는 말한다',
    grammar: '동사 1단 현재', baseForm: 'vadati',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '👤', word: 'yo', pronKo: '요', meaning: '~한 자가 (관계대명사 주격 남성)',
    grammar: '관계대명사, 주격 남성 단수', baseForm: 'ya-',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '☸️', word: 'ariyasaccāni', pronKo: '아리야삿짜~니', meaning: '성스러운 진리들 (대격 복수)',
    grammar: '복합어, 대격 중성 복수', baseForm: 'ariya + sacca',
    formNote: '11과 MN10 V_SAC0과 동일',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '🔍', word: 'avecca', pronKo: '아웻짜', meaning: '꿰뚫어, 통찰하여 (절대분사)',
    grammar: '절대분사', baseForm: 'avecca',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '👁️', word: 'passati', pronKo: '빳사띠', meaning: '본다',
    grammar: '동사 3단 현재', baseForm: 'passati (√das)',
    verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'verse', pali: V6, pronKo: '야틴다키~로 빠타윗시또 시야~, 짜뚭비 와~떼히 아삼빠깜삐요. 따투~빠망 삽뿌리상 와다~미, 요 아리야삿짜~니 아웻짜 빳사띠. 이담삐 상게 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V6K, highlight: ['Yathindakhīlo','pathavissito','asampakampiyo','sappurisaṃ','vadāmi','yo','ariyasaccāni','avecca','passati'],
    note: '🗿 인드라 석주 비유 — 흔들리지 않는 예류자.' },

  // ===== V7: 8생 안 옴 =====
  { type: 'teach', icon: '🧠', word: 'vibhāvayanti', pronKo: '위바~와얀띠', meaning: '꿰뚫어 본다 (3복)',
    grammar: '동사 3복 현재', baseForm: 'vibhāveti',
    verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '🧠', word: 'gambhīrapaññena', pronKo: '감비~라빤녜나', meaning: '심오한 지혜로 (도구격)',
    grammar: '복합어, 도구격', baseForm: 'gambhīra(심오) + paññā',
    verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '🎤', word: 'sudesitāni', pronKo: '수데시따~니', meaning: '잘 설해진 (대격 복수)',
    grammar: '과거분사, 대격 중성 복수', baseForm: 'su + desita',
    verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '➕', word: 'Kiñcāpi', pronKo: '낀짜~삐', meaning: '비록 ~하더라도',
    grammar: '복합 양보', baseForm: 'kiñ + ca + api',
    verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '⚠️', word: 'bhusaṃ', pronKo: '부상', meaning: '강하게, 크게',
    grammar: '부사', baseForm: 'bhusa',
    verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '😴', word: 'pamattā', pronKo: '빠맛따~', meaning: '방일한 (주격 복수)',
    grammar: '과거분사, 주격 복수', baseForm: 'pamatta',
    formNote: '11과 MN10·6과 mangala의 pamāda와 같은 어원',
    verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '♾️', word: 'bhavaṃ', pronKo: '바왕', meaning: '존재를 (대격)',
    grammar: '남성명사, 대격', baseForm: 'bhava',
    formNote: '11과 MN10 V_SAM_S0의 bhavataṇhā와 같은 단어',
    verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '7️⃣', word: 'aṭṭhamamādiyanti', pronKo: '앗타마마~디얀띠', meaning: '여덟 번째를 받는다',
    grammar: '복합 + 동사 3복', baseForm: 'aṭṭhamaṃ + ādiyati',
    formNote: '"na ... aṭṭhamamādiyanti" = "여덟 번째 (생을) 받지 않는다"',
    buddhism: '예류자 최대 7생 안에 아라한 — 8번째는 없음.',
    verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'verse', pali: V7, pronKo: '예 아리야삿짜~니 위바~와얀띠, 감비~라빤녜나 수데시따~니. 낀짜~삐 떼 혼띠 부상 빠맛따~, 나 떼 바왕 앗타마마~디얀띠. 이담삐 상게 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V7K, highlight: ['vibhāvayanti','gambhīrapaññena','sudesitāni','Kiñcāpi','bhusaṃ','pamattā','bhavaṃ','aṭṭhamam'],
    note: '7️⃣ 예류자 최대 7생 보장.' },

  // ===== V8: 3결 + 4악도 + 6중죄 =====
  { type: 'teach', icon: '🤝', word: 'Sahāvassa', pronKo: '사하~왓사', meaning: '그에게 동시에 (saha + assa)',
    grammar: '부사 + 속격', baseForm: 'saha(함께) + assa(그의)',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '👁️', word: 'dassanasampadāya', pronKo: '닷사나삼빠다~야', meaning: '봄의 성취와 함께 (도구격)',
    grammar: '복합어, 도구격', baseForm: 'dassana + sampadā',
    buddhism: '예류과의 표지 = 사성제 직관.',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '3️⃣', word: 'tayassu dhammā', pronKo: '따얏수 담마~', meaning: '세 법이',
    grammar: '수사 + 주격 + 명사 주격 복수', baseForm: 'tayo + assu(강조) + dhamma',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '🧹', word: 'jahitā', pronKo: '자히따~', meaning: '버려진 (주격 복수)',
    grammar: '과거분사, 주격 복수', baseForm: 'jahita',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '👤', word: 'sakkāyadiṭṭhi', pronKo: '삭까~야딧티', meaning: '유신견',
    grammar: '복합어, 주격', baseForm: 'sakkāya + diṭṭhi',
    buddhism: '3결의 첫째 — "이것이 나"라는 견해.',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '❓', word: 'vicikicchitaṃ', pronKo: '위찌낏치땅', meaning: '의심',
    grammar: '복합어, 주격 중성', baseForm: 'vicikicchitā',
    formNote: '11과 MN10 V_NIV5의 vicikicchā와 동일',
    buddhism: '3결의 둘째.',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '📿', word: 'sīlabbataṃ', pronKo: '시~랍바땅', meaning: '계금취',
    grammar: '복합어, 주격', baseForm: 'sīla + bbata (vata 의례)',
    buddhism: '3결의 셋째 — 잘못된 의례·금기 집착.',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '⛔', word: 'catūhapāyehi', pronKo: '짜뚜~하빠~예히', meaning: '네 악도에서 (탈격 복수)',
    grammar: '복합어, 탈격 복수', baseForm: 'catur + apāya',
    buddhism: '4악도: 지옥·축생·아귀·아수라.',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '🆓', word: 'vippamutto', pronKo: '윕빠뭇또', meaning: '벗어난 (주격)',
    grammar: '과거분사, 주격', baseForm: 'vippamutta',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '6️⃣', word: 'chaccābhiṭhānāni', pronKo: '찻짜~비타~나~니', meaning: '여섯 큰 죄들 (주격 복수)',
    grammar: '복합어, 주격 중성 복수', baseForm: 'cha + abhiṭhāna',
    buddhism: '6중죄: 5무간업 + 이단(외도).',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '🚫', word: 'abhabba', pronKo: '압밥바', meaning: '불가능한',
    grammar: '형용사', baseForm: 'a + bhabba',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'teach', icon: '⚒️', word: 'kātuṃ', pronKo: '까~뚱', meaning: '행하기 (부정사)',
    grammar: '부정사', baseForm: 'karoti',
    verseLine: V8, verseLineKo: V8K, audio: true },
  { type: 'verse', pali: V8, pronKo: '사하~왓사 닷사나삼빠다~야, 따얏수 담마~ 자히따~ 바완띠. 삭까~야딧티 위찌낏치딴짜, 시~랍바땅 와~삐 야닷티 낀찌. 짜뚜~하빠~예히 짜 윕빠뭇또, 찻짜~비타~나~니 압밥바 까~뚱. 이담삐 상게 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V8K, highlight: ['Sahāvassa','dassanasampadāya','tayassu','jahitā','sakkāyadiṭṭhi','vicikicchitaṃ','sīlabbataṃ','catūhapāyehi','vippamutto','chaccābhiṭhānāni','abhabba','kātuṃ'],
    note: '🚫 예류자 — 3결 끊음 + 4악도 탈출 + 6중죄 불가.' },

  // ===== V9: 예류자 죄 못 감춤 =====
  { type: 'teach', icon: '💀', word: 'kamma karoti pāpakaṃ', pronKo: '깜마 까로띠 빠~빠깡', meaning: '악업을 짓는다',
    grammar: '대격+동사+형용사', baseForm: 'kamma + karoti + pāpaka',
    verseLine: V9, verseLineKo: V9K, audio: true },
  { type: 'teach', icon: '🤚', word: 'kāyena vācā uda cetasā', pronKo: '까~예나 와~짜~ 우다 쩨따사~', meaning: '몸·말·뜻으로 (도구격)',
    grammar: '도구격 3개', baseForm: 'kāya + vācā + ceto',
    formNote: 'uda = "또는, 혹은"',
    buddhism: '신·구·의 3업.',
    verseLine: V9, verseLineKo: V9K, audio: true },
  { type: 'teach', icon: '🫥', word: 'paṭicchadāya', pronKo: '빠띳차다~야', meaning: '감추기 위해 (여격)',
    grammar: '여격', baseForm: 'paṭicchadana',
    verseLine: V9, verseLineKo: V9K, audio: true },
  { type: 'teach', icon: '🚫', word: 'abhabbatā', pronKo: '압밥바따~', meaning: '불가능함 (주격)',
    grammar: '여성명사, 주격', baseForm: 'abhabba + tā',
    verseLine: V9, verseLineKo: V9K, audio: true },
  { type: 'teach', icon: '👁️', word: 'diṭṭhapadassa', pronKo: '딧타빠닷사', meaning: '길을 본 자의 (속격)',
    grammar: '복합어, 속격', baseForm: 'diṭṭha + pada',
    buddhism: '예류자(길/도를 본 자).',
    verseLine: V9, verseLineKo: V9K, audio: true },
  { type: 'teach', icon: '🗣️', word: 'vuttā', pronKo: '웃따~', meaning: '말해진 (과거분사 주격)',
    grammar: '과거분사', baseForm: 'vutta',
    verseLine: V9, verseLineKo: V9K, audio: true },
  { type: 'verse', pali: V9, pronKo: '낀짜~삐 소 깜마 까로띠 빠~빠깡, 까~예나 와~짜~ 우다 쩨따사~ 와~. 압밥바 소 땃사 빠띳차다~야, 압밥바따~ 딧타빠닷사 웃따~. 이담삐 상게 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V9K, highlight: ['kamma','pāpakaṃ','kāyena','vācā','cetasā','paṭicchadāya','abhabbatā','diṭṭhapadassa','vuttā'],
    note: '👁️ 예류자는 자동 참회.' },

  // ===== V10: 꽃핀 숲 비유 =====
  { type: 'teach', icon: '🌳', word: 'Vanappagumbe', pronKo: '와납빠굼베', meaning: '숲에서 (처격)',
    grammar: '복합어, 처격', baseForm: 'vana + pagumba',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'teach', icon: '🟰', word: 'yatha', pronKo: '야타', meaning: '~처럼',
    grammar: '부사', baseForm: 'yathā (단축)',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'teach', icon: '🌸', word: 'phussitagge', pronKo: '풋시딱게', meaning: '꼭대기까지 꽃핀 (처격)',
    grammar: '복합어, 처격', baseForm: 'phussita + agga',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'teach', icon: '☀️', word: 'gimhānamāse', pronKo: '김하~나마~세', meaning: '여름 달에 (처격)',
    grammar: '복합어, 처격', baseForm: 'gimhāna + māsa',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'teach', icon: '1️⃣', word: 'paṭhamasmiṃ gimhe', pronKo: '빠타마스밍 김헤', meaning: '첫 여름에 (처격)',
    grammar: '서수+명사 처격', baseForm: 'paṭhama + gimha',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'teach', icon: '🌟', word: 'dhammavaraṃ', pronKo: '담마와랑', meaning: '뛰어난 담마 (대격)',
    grammar: '복합어, 대격', baseForm: 'dhamma + vara (최고)',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'teach', icon: '📢', word: 'adesayi', pronKo: '아데사이', meaning: '설하셨다 (3단 아오리스트)',
    grammar: '동사 3단 아오리스트', baseForm: 'deseti',
    formNote: '5과 sn45-8의 desessāmi(미래)와 같은 어근',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'teach', icon: '🛤️', word: 'nibbānagāmiṃ', pronKo: '닙바~나가~밍', meaning: '열반으로 이끄는 (대격)',
    grammar: '복합어, 대격', baseForm: 'nibbāna + gāmin',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'teach', icon: '🏆', word: 'paramaṃ hitāya', pronKo: '빠라망 히따~야', meaning: '최상의 이익을 위해',
    grammar: '형용사+여격', baseForm: 'parama + hita',
    verseLine: V10, verseLineKo: V10K, audio: true },
  { type: 'verse', pali: V10, pronKo: '와납빠굼베 야타 풋시딱게, 김하~나마~세 빠타마스밍 김헤. 따투~빠망 담마와랑 아데사이, 닙바~나가~밍 빠라망 히따~야. 이담삐 붓데 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V10K, highlight: ['Vanappagumbe','phussitagge','gimhānamāse','dhammavaraṃ','adesayi','nibbānagāmiṃ','paramaṃ','hitāya'],
    note: '🌸 담마 = 꽃핀 숲처럼 아름답고 시원함.' },

  // ===== V11: 4중 vara =====
  { type: 'teach', icon: '👑', word: 'Varo', pronKo: '와로', meaning: '최고이신 분 (주격)',
    grammar: '형용사, 주격', baseForm: 'vara',
    verseLine: V11, verseLineKo: V11K, audio: true },
  { type: 'teach', icon: '🌌', word: 'varaññū', pronKo: '와란뉴~', meaning: '최고를 아시는 분',
    grammar: '복합어, 주격', baseForm: 'vara + ññū',
    verseLine: V11, verseLineKo: V11K, audio: true },
  { type: 'teach', icon: '🎁', word: 'varado', pronKo: '와라도', meaning: '최고를 주시는 분',
    grammar: '복합어, 주격', baseForm: 'vara + da',
    verseLine: V11, verseLineKo: V11K, audio: true },
  { type: 'teach', icon: '🚚', word: 'varāharo', pronKo: '와라~하로', meaning: '최고를 가져오신 분',
    grammar: '복합어, 주격', baseForm: 'vara + āhara',
    verseLine: V11, verseLineKo: V11K, audio: true },
  { type: 'teach', icon: '👑', word: 'anuttaro', pronKo: '아눗따로', meaning: '무상하신 (주격)',
    grammar: '형용사, 주격', baseForm: 'an + uttara',
    formNote: '11과 MN10 V_CIT2의 anuttaraṃ과 같은 단어',
    buddhism: '무상(無上).',
    verseLine: V11, verseLineKo: V11K, audio: true },
  { type: 'verse', pali: V11, pronKo: '와로 와란뉴~ 와라도 와라~하로, 아눗따로 담마와랑 아데사이. 이담삐 붓데 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V11K, highlight: ['Varo','varaññū','varado','varāharo','anuttaro','dhammavaraṃ'],
    note: '👑 부처님 4중 vara 칭송.' },

  // ===== V12: 등불 비유 =====
  { type: 'teach', icon: '🌑', word: 'Khīṇaṃ purāṇaṃ', pronKo: '키~낭 뿌라~낭', meaning: '옛 (업)은 다하고',
    grammar: '과거분사+형용사', baseForm: 'khīṇa + purāṇa',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '🆕', word: 'nava', pronKo: '나와', meaning: '새로운',
    grammar: '형용사', baseForm: 'nava',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '🚫', word: 'natthi sambhavaṃ', pronKo: '낫티 삼바왕', meaning: '발생이 없다',
    grammar: '부정+동사+주격', baseForm: 'na+atthi + sambhava',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '🌫️', word: 'virattacittā', pronKo: '위랏따찟따~', meaning: '탐욕을 떠난 마음의 (주격 복수)',
    grammar: '복합어, 주격 복수', baseForm: 'viratta + citta',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '⏭️', word: 'āyatike bhavasmiṃ', pronKo: '아~야띠께 바와스밍', meaning: '미래 존재에 (처격)',
    grammar: '형용사+명사 처격', baseForm: 'āyatika + bhava',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '🌱', word: 'khīṇabījā', pronKo: '키~나비~자~', meaning: '종자 다한 (주격 복수)',
    grammar: '복합어, 주격 복수', baseForm: 'khīṇa + bīja',
    buddhism: '윤회의 종자 = 갈애·무명.',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '🚫', word: 'avirūḷhichandā', pronKo: '아위루~흘리찬다~', meaning: '자라남의 의욕 없는',
    grammar: '복합어, 주격 복수', baseForm: 'a + virūḷhi + chanda',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '🔥', word: 'nibbanti', pronKo: '닙반띠', meaning: '꺼진다 (3복)',
    grammar: '동사 3복 현재', baseForm: 'nibbāyati',
    formNote: 'nibbāna(열반)의 동사형 — "꺼지다"',
    buddhism: '반열반.',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '🧙', word: 'dhīrā', pronKo: '디~라~', meaning: '지혜로운 자들 (주격 복수)',
    grammar: '형용사, 주격 복수', baseForm: 'dhīra',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '🟰', word: 'yathāyaṃ', pronKo: '야타~양', meaning: '이 ~처럼',
    grammar: '비교+지시', baseForm: 'yathā + ayaṃ',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'teach', icon: '💡', word: 'padīpo', pronKo: '빠디~뽀', meaning: '등불 (주격)',
    grammar: '남성명사, 주격', baseForm: 'padīpa',
    verseLine: V12, verseLineKo: V12K, audio: true },
  { type: 'verse', pali: V12, pronKo: '키~낭 뿌라~낭 나와 낫티 삼바왕, 위랏따찟따~야띠께 바와스밍. 떼 키~나비~자~ 아위루~흘리찬다~, 닙반띠 디~라~ 야타~양 빠디~뽀. 이담삐 상게 라따낭 빠니~땅, 에떼나 삿쩨나 수왓티 호뚜.',
    translation: V12K, highlight: ['Khīṇaṃ','purāṇaṃ','nava','sambhavaṃ','virattacittā','khīṇabījā','avirūḷhichandā','nibbanti','dhīrā','padīpo'],
    note: '💡 아라한 = 꺼지는 등불.' },

  // ===== V13-V15: 결어 (3보 예배) =====
  { type: 'intro', icon: '🙏', title: '— 결어: 3보 예배 (V13-V15) —', subtitle: '붓다·담마·상가 차례로',
    description: '천신들이 모인 자리에서 3보께 예배.' },
  { type: 'teach', icon: '👼', word: 'Tathāgataṃ', pronKo: '따타~가땅', meaning: '여래를 (대격)',
    grammar: '남성명사, 대격', baseForm: 'tathāgata',
    verseLine: V13, verseLineKo: V13K, audio: true },
  { type: 'teach', icon: '🌟', word: 'devamanussapūjitaṃ', pronKo: '데와마눗사뿌~지땅', meaning: '신과 인간이 공양하는 (대격)',
    grammar: '복합어, 대격', baseForm: 'deva + manussa + pūjita',
    verseLine: V13, verseLineKo: V13K, audio: true },
  { type: 'teach', icon: '☸️', word: 'buddhaṃ', pronKo: '붓당', meaning: '붓다를 (대격)',
    grammar: '남성명사, 대격', baseForm: 'buddha',
    verseLine: V13, verseLineKo: V13K, audio: true },
  { type: 'teach', icon: '🙏', word: 'namassāma', pronKo: '나맛사~마', meaning: '우리는 예배한다 (1복)',
    grammar: '동사 1복 현재', baseForm: 'namassati',
    verseLine: V13, verseLineKo: V13K, audio: true },
  { type: 'verse', pali: V13, pronKo: '야~니~다 부~따~니 사마~가따~니, 붐마~니 와~ 야~니 와 안딸릭케. 따타~가땅 데와마눗사뿌~지땅, 붓당 나맛사~마 수왓티 호뚜.',
    translation: V13K, highlight: ['Tathāgataṃ','devamanussapūjitaṃ','buddhaṃ','namassāma'],
    note: '🙏 붓다 예배.' },

  { type: 'teach', icon: '📜', word: 'dhammaṃ', pronKo: '담망', meaning: '담마를 (대격)',
    grammar: '남성명사, 대격', baseForm: 'dhamma',
    verseLine: V14, verseLineKo: V14K, audio: true },
  { type: 'verse', pali: V14, pronKo: '야~니~다 부~따~니... 따타~가땅 데와마눗사뿌~지땅, 담망 나맛사~마 수왓티 호뚜.',
    translation: V14K, highlight: ['dhammaṃ','namassāma'],
    note: '🙏 담마 예배.' },

  { type: 'teach', icon: '🧘', word: 'saṅghaṃ', pronKo: '상강', meaning: '상가를 (대격)',
    grammar: '남성명사, 대격', baseForm: 'saṅgha',
    verseLine: V15, verseLineKo: V15K, audio: true },
  { type: 'verse', pali: V15, pronKo: '야~니~다 부~따~니... 따타~가땅 데와마눗사뿌~지땅, 상강 나맛사~마 수왓티 호뚜~띠.',
    translation: V15K, highlight: ['saṅghaṃ','namassāma'],
    note: '🙏 상가 예배 — 보배경 완결.' },

  { type: 'verse', pali: 'ratanasuttaṃ niṭṭhitaṃ.', pronKo: '라따나숫땅 닛티땅.', translation: '— 보배경 끝 —' },

  // ===== 종합 =====
  { type: 'teach-grammar', title: '진실 서원 (Saccakiriyā) 구조',
    example: 'idampi buddhe ratanaṃ paṇītaṃ. etena saccena suvatthi hotu.',
    exampleKo: '이것이 붓다 안의 뛰어난 보배. 이 진실에 의해 행복이 있기를.',
    explanation: '보배경의 반복 후렴:\n• idampi (이것 또한) + [삼보 처격] + ratanaṃ paṇītaṃ\n• etena saccena (이 진실에 의해) + suvatthi hotu (행복이 있기를)\n\n삼보의 공덕 = "진실(sacca)" → 그 진실에 의해 가피.' },

  { type: 'quiz', question: '경의 첫 단어 "Yānīdha"는 어떤 두 단어의 결합?',
    options: ['yāni + idha', 'yaṃ + idha', 'yāva + idha', 'yathā + idha'], answer: 0,
    hint: '관계대명사 yāni + 처격부사 idha' },
  { type: 'quiz', question: 'V1 첫 단어 "Yaṃ"은?',
    options: ['관계대명사 주격/대격 중성 단수', '시간 부사', '강조사', '부정사'], answer: 0 },
  { type: 'quiz', question: '후렴 "etena saccena suvatthi hotu"의 뜻?',
    options: ['이 진실에 의해 행복이 있기를', '이 법을 따르라', '이 보배에 귀의', '이 진실을 기억하라'], answer: 0 },
  { type: 'quiz', question: '예류자가 끊는 3결은?',
    options: ['유신견·의심·계금취', '탐·진·치', '계·정·혜', '신·구·의'], answer: 0 },
  { type: 'quiz', question: '예류자의 보장은?',
    options: ['7생 안에 아라한과', '천상 출생', '즉시 부처', '신통 획득'], answer: 0 },
  { type: 'quiz', question: '아라한 비유 (V12)는?',
    options: ['꺼지는 등불', '구름 흩어짐', '강의 흐름', '꽃이 핌'], answer: 0,
    hint: 'nibbanti dhīrā yathāyaṃ padīpo' },
  { type: 'quiz', question: '보배경 결어에서 3보 예배 순서는?',
    options: ['붓다 → 담마 → 상가', '상가 → 담마 → 붓다', '담마 → 붓다 → 상가', '동시'], answer: 0 },

  { type: 'speak', pali: 'etena saccena suvatthi hotu.', pronKo: '에떼나 삿쩨나 수왓티 호뚜.' },
  { type: 'speak', pali: V1, pronKo: '양 낀찌 윗땅 이다 와~ 후랑 와~...' },

  { type: 'arrange', instruction: '빠알리 문장을 순서대로 배열하세요.',
    translation: '이 진실에 의해 행복이 있기를.',
    blocks: ['saccena', 'etena', 'hotu.', 'suvatthi'],
    correctOrder: [1, 0, 3, 2] },
]
