// 전법륜경(SN 56.11) 학습 데이터 — 모든 문장, 모든 단어
// 타입은 ScriptureLearn.tsx에서 가져옴

const V1 = 'Ekaṃ samayaṃ bhagavā bārāṇasiyaṃ viharati isipatane migadāye.'
const V1K = '한 때 세존께서 바라나시의 녹야원, 이시빠따나에 머무셨다.'
const V2 = 'Tatra kho bhagavā pañcavaggiye bhikkhū āmantesi:'
const V2K = '거기서 세존께서 다섯 비구에게 말씀하셨다:'
const V3 = '"Dveme, bhikkhave, antā pabbajitena na sevitabbā."'
const V3K = '"비구들이여, 출가자가 따르지 말아야 할 두 극단이 있다."'
const V4 = 'Ete kho, bhikkhave, ubho ante anupagamma majjhimā paṭipadā tathāgatena abhisambuddhā'
const V4K = '이 양극단에 다가가지 않고, 여래가 깨달은 중도가 있으니'
const V5 = 'Ayameva ariyo aṭṭhaṅgiko maggo, seyyathidaṃ—sammādiṭṭhi sammāsaṅkappo sammāvācā sammākammanto sammāājīvo sammāvāyāmo sammāsati sammāsamādhi.'
const V5K = '그것은 바로 성스러운 팔정도이니—바른 견해, 바른 사유, 바른 말, 바른 행위, 바른 생계, 바른 정진, 바른 마음챙김, 바른 삼매이다.'
const V6 = 'Idaṃ kho pana, bhikkhave, dukkhaṃ ariyasaccaṃ—'
const V6K = '비구들이여, 이것이 괴로움의 성스러운 진리이다—'
const V7 = 'jātipi dukkhā, jarāpi dukkhā, byādhipi dukkho, maraṇampi dukkhaṃ'
const V7K = '태어남도 괴로움, 늙음도 괴로움, 병듦도 괴로움, 죽음도 괴로움이다'

export type StepType =
  | { type: 'intro'; title: string; subtitle: string; description: string; icon: string }
  | { type: 'teach'; word: string; pronKo: string; meaning: string; icon: string; buddhism?: string; audio?: boolean; verseLine?: string; verseLineKo?: string; grammar?: string; baseForm?: string; formNote?: string }
  | { type: 'teach-grammar'; title: string; example: string; exampleKo: string; explanation: string }
  | { type: 'verse'; pali: string; pronKo: string; translation: string; highlight?: string[]; note?: string }
  | { type: 'quiz'; question: string; options: string[]; answer: number; hint?: string }
  | { type: 'speak'; pali: string; pronKo: string }
  | { type: 'match-listen'; instruction: string; word: string; pronKo: string; options: string[]; answer: number }
  | { type: 'match-reverse'; instruction: string; meaning: string; options: string[]; answer: number }
  | { type: 'writing'; instruction: string; meaning: string; pronKo: string; answer: string; hint?: string }
  | { type: 'arrange'; instruction: string; translation: string; blocks: string[]; correctOrder: number[] }

export const LESSON_SN56_11: StepType[] = [
  // ===== 경전 소개 =====
  { type: 'intro', icon: '☸️', title: '전법륜경', subtitle: 'Dhammacakkappavattana Sutta (SN 56.11)',
    description: '붓다가 깨달음을 이룬 후\n다섯 수행자에게 처음으로 설한 가르침.\n\n첫 문장부터 한 단어씩 배워봅시다.' },

  // ===== 1문장 (7단어) =====
  { type: 'teach', icon: '1️⃣', word: 'ekaṃ', pronKo: '에깡', meaning: '하나의, 어떤',
    grammar: '수사, 대격', baseForm: 'eka (하나)', formNote: 'eka → ekaṃ: 대격 어미 -ṃ. "하나의(때를)"', verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '⏰', word: 'samayaṃ', pronKo: '사마양', meaning: '때, 시기',
    grammar: '남성명사, 대격 단수', baseForm: 'samaya (때)', formNote: 'samaya → samayaṃ: -a 어간 대격 -ṃ. "ekaṃ samayaṃ" = 한 때에', verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach-grammar', title: '대격 어미 -ṃ', example: 'eka → ekaṃ\nsamaya → samayaṃ', exampleKo: '하나 → 하나의(를)\n때 → 때(를)',
    explanation: '남성/중성 -a 어간 대격에서 -ṃ이 붙음.\n대격 = 목적어 "~을/를" 또는 시간 표현.' },
  { type: 'teach', icon: '🙏', word: 'bhagavā', pronKo: '바가와~', meaning: '세존께서',
    grammar: '남성명사, 주격 단수', baseForm: 'bhagavant (복덕 있는 분)', formNote: 'bhagavant → bhagavā: 특수 어간(-ant) 주격형.\n주격 = "~이/가" (주어)',
    buddhism: '세존(世尊). 붓다의 존칭. "복덕을 갖추신 분".', verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'quiz', question: '"ekaṃ samayaṃ bhagavā"의 뜻은?', options: ['한 때 세존께서', '모든 비구들이', '괴로움의 원인은', '법의 바퀴를'], answer: 0 },
  { type: 'teach', icon: '📍', word: 'bārāṇasiyaṃ', pronKo: '바~라~나시양', meaning: '바라나시에서',
    grammar: '여성명사, 처격(7격)', baseForm: 'Bārāṇasī', formNote: '-ī 어간 처격 어미 -iyaṃ = "~에서"',
    buddhism: '바라나시. 붓다 첫 설법지.', verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '🏠', word: 'viharati', pronKo: '위하라띠', meaning: '머무시다',
    grammar: '동사, 현재 3인칭 단수', baseForm: '√vi-har (머물다)', formNote: '어근 √har + 접두사 vi. 경전 서두 정형구에 항상 나옴.',
    buddhism: 'vihāra(정사, 사원)와 같은 어근.', verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '🏔️', word: 'isipatane', pronKo: '이시빠따네', meaning: '이시빠따나에',
    grammar: '중성명사, 처격(7격)', baseForm: 'Isipatana', formNote: '-a 어간 처격 어미 -e = "~에"',
    buddhism: '"선인(isi)들이 내려온(patana) 곳". 녹야원의 다른 이름.', verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach', icon: '🦌', word: 'migadāye', pronKo: '미가다~예', meaning: '녹야원에',
    grammar: '남성명사, 처격(7격)', baseForm: 'migadāya (사슴+동산)', formNote: 'miga(사슴) + dāya(동산). -a 어간 처격 -e',
    buddhism: '녹야원(鹿野苑). 현재 사르나트(Sarnath). 붓다 최초 설법지.', verseLine: V1, verseLineKo: V1K, audio: true },
  { type: 'teach-grammar', title: '처격(7격) -e / -iyaṃ', example: 'migadāya → migadāye\nBārāṇasī → bārāṇasiyaṃ', exampleKo: '녹야원 → 녹야원에\n바라나시 → 바라나시에서',
    explanation: '처격 = "~에서, ~안에" (장소)\n-a 어간: -e / -ī 어간: -iyaṃ' },
  { type: 'verse', pali: V1, pronKo: '에깡 사마양 바가와~ 바~라~나시양 위하라띠 이시빠따네 미가다~예.',
    translation: V1K, highlight: ['ekaṃ','samayaṃ','bhagavā','bārāṇasiyaṃ','viharati','isipatane','migadāye'],
    note: '✅ 첫 문장 7단어 완료! 탭해서 복습하세요.' },
  { type: 'quiz', question: '"viharati"의 뜻은?', options: ['말하다', '머무시다', '걷다', '앉다'], answer: 1 },
  { type: 'quiz', question: '"migadāye"의 -e는 무슨 격?', options: ['주격', '대격', '처격', '속격'], answer: 2 },
  { type: 'writing', instruction: '"세존"을 빠알리어로 써보세요', meaning: '세존 (붓다의 존칭)', pronKo: '바가와~', answer: 'bhagavā', hint: 'bh로 시작, ā로 끝남' },
  { type: 'writing', instruction: '"머무시다"를 빠알리어로 써보세요', meaning: '머무시다 (동사 현재)', pronKo: '위하라띠', answer: 'viharati', hint: 'v로 시작' },
  { type: 'speak', pali: V1, pronKo: '에깡 사마양 바가와~ 바~라~나시양 위하라띠 이시빠따네 미가다~예.' },

  // ===== 2문장 (5단어) =====
  { type: 'teach', icon: '👉', word: 'tatra', pronKo: '따뜨라', meaning: '거기서',
    grammar: '부사 (불변어)', formNote: '변하지 않는 단어. 격변화 없음.', verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '❗', word: 'kho', pronKo: '코', meaning: '실로, 참으로',
    grammar: '강조 불변어', formNote: '문장 강조. 영어 indeed. 경전에 매우 자주 나옴.', verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '5️⃣', word: 'pañcavaggiye', pronKo: '빤짜왁기예', meaning: '다섯 무리의',
    grammar: '형용사, 대격 복수', baseForm: 'pañcavaggiya', formNote: 'pañca(다섯)+vaggiya(무리의). 대격 복수 -e',
    buddhism: '다섯 비구(五比丘). 꼰단냐, 왑빠, 밧디야, 마하나마, 앗사지.', verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach', icon: '🧘', word: 'bhikkhū', pronKo: '빅쿠~', meaning: '비구들을',
    grammar: '남성명사, 대격 복수', baseForm: 'bhikkhu (비구)',
    formNote: 'bhikkhu 격변화:\n• 주격 단수: bhikkhu (비구가)\n• 대격 복수: bhikkhū (비구들을) ← 여기!\n• 호격 복수: bhikkhave (비구들이여)\n\n대격 복수 = 주격 복수와 같은 형태(bhikkhū)',
    buddhism: '비구(比丘). 출가 수행자. "걸식하는 자".', verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'teach-grammar', title: 'bhikkhu(비구) 격변화', example: 'bhikkhu → bhikkhū → bhikkhave', exampleKo: '비구가 → 비구들을 → 비구들이여',
    explanation: '-u 어간 남성명사:\n• 주격: bhikkhu / bhikkhū\n• 대격: bhikkhuṃ / bhikkhū\n• 호격: bhikkhu / bhikkhave\n\n💡 대격 복수 = 주격 복수(bhikkhū)' },
  { type: 'teach', icon: '🗣️', word: 'āmantesi', pronKo: '아~만떼시', meaning: '말씀하셨다',
    grammar: '동사, 과거(aorist) 3인칭 단수', baseForm: '√manteti (부르다)',
    formNote: 'ā(접두사) + mantesi(과거형).\n현재: manteti "부른다"\n과거: āmantesi "불렀다"',
    verseLine: V2, verseLineKo: V2K, audio: true },
  { type: 'verse', pali: V2, pronKo: '따뜨라 코 바가와~ 빤짜왁기예 빅쿠~ 아~만떼시:',
    translation: V2K, highlight: ['tatra','kho','bhagavā','pañcavaggiye','bhikkhū','āmantesi'],
    note: '✅ 두 번째 문장 완료! bhagavā가 다시 나왔죠?' },
  { type: 'quiz', question: '"bhikkhū"와 "bhikkhave"의 차이는?', options: ['bhikkhū=대격(~을), bhikkhave=호격(~이여)', '같은 뜻', 'bhikkhū=단수, bhikkhave=복수', 'bhikkhū=과거, bhikkhave=현재'], answer: 0, hint: '격이 다릅니다' },
  { type: 'quiz', question: '"āmantesi"는 어떤 시제?', options: ['현재', '과거', '미래', '명령'], answer: 1 },
  { type: 'writing', instruction: '"비구들을"을 빠알리어로 써보세요', meaning: '비구들을 (대격 복수)', pronKo: '빅쿠~', answer: 'bhikkhū', hint: 'bhikkhu의 대격 복수' },
  { type: 'writing', instruction: '"말씀하셨다"를 빠알리어로 써보세요', meaning: '말씀하셨다 (과거)', pronKo: '아~만떼시', answer: 'āmantesi' },
  { type: 'arrange', instruction: '문장을 올바른 순서로 배열하세요', translation: '거기서 세존께서 다섯 비구에게 말씀하셨다',
    blocks: ['āmantesi', 'bhagavā', 'bhikkhū', 'pañcavaggiye', 'tatra', 'kho'], correctOrder: [4, 5, 1, 3, 2, 0] },
  { type: 'speak', pali: V2, pronKo: '따뜨라 코 바가와~ 빤짜왁기예 빅쿠~ 아~만떼시:' },

  // ===== 3문장: 두 극단 (6단어) =====
  { type: 'teach', icon: '2️⃣', word: 'dveme', pronKo: '드웨메', meaning: '이 두 가지',
    grammar: '수사+대명사', baseForm: 'dve (둘) + ime (이것들)', formNote: 'dve(둘)+ime(이것들) 합쳐진 형태.',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '🧘', word: 'bhikkhave', pronKo: '빅카웨', meaning: '비구들이여',
    grammar: '남성명사, 호격 복수', baseForm: 'bhikkhu (비구)',
    formNote: '호격(8격) = 부르는 말 "~이여!"\nbhikkhu → bhikkhave (호격 복수)\n\n💡 앞에서 배운 bhikkhū(대격)과 비교:\n• bhikkhū = 비구들을 (목적어)\n• bhikkhave = 비구들이여 (호칭)',
    buddhism: '경전에서 붓다가 제자를 부를 때. 가장 자주 나오는 호칭.', verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '⚡', word: 'antā', pronKo: '안따~', meaning: '극단들이',
    grammar: '남성명사, 주격 복수', baseForm: 'anta (극단, 끝)',
    formNote: 'anta → antā: -a 어간 주격 복수 어미 -ā',
    buddhism: '극단(極端). 붓다는 쾌락과 고행 양극단을 피하고 중도를 가르침.', verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '🚶', word: 'pabbajitena', pronKo: '빱바지떼나', meaning: '출가자에 의해',
    grammar: '남성명사, 구격(3격) 단수', baseForm: 'pabbajita (출가자)',
    formNote: 'pabbajita → pabbajitena: -a 어간 구격 -ena = "~에 의해, ~로써"',
    buddhism: '출가자. 세속을 떠나 수행하는 자. pabbajjā(출가)에서 유래.', verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '🚫', word: 'na', pronKo: '나', meaning: '~않다',
    grammar: '부정 불변어', formNote: '부정을 나타냄. 영어 not. 동사/형용사 앞에 위치.', verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach', icon: '📋', word: 'sevitabbā', pronKo: '세위땁바~', meaning: '따라야 할, 섬겨야 할',
    grammar: '의무분사(미래수동분사), 주격 복수', baseForm: '√sev (따르다, 섬기다)',
    formNote: '√sev → sevitabba: -tabba 어미 = "~해야 할" (의무/당위)\n"na sevitabbā" = "따르지 말아야 할"',
    verseLine: V3, verseLineKo: V3K, audio: true },
  { type: 'teach-grammar', title: '구격(3격) -ena / 의무분사 -tabba', example: 'pabbajita → pabbajitena\n√sev → sevitabbā', exampleKo: '출가자 → 출가자에 의해\n따르다 → 따라야 할',
    explanation: '구격(-ena) = "~에 의해, ~로써"\n의무분사(-tabba) = "~해야 할" (영어 should)\n"na sevitabbā" = 따르지 말아야 할\n"pabbajitena" = 출가자에 의해' },
  { type: 'verse', pali: V3, pronKo: '"드웨메, 빅카웨, 안따~ 빱바지떼나 나 세위땁바~."',
    translation: V3K, highlight: ['dveme','bhikkhave','antā','pabbajitena','na','sevitabbā'],
    note: '☸️ 붓다의 첫 설법이 시작됩니다! "두 극단을 따르지 말라"' },
  { type: 'quiz', question: '"na sevitabbā"의 뜻은?', options: ['따라야 한다', '따르지 말아야 할', '이미 따랐다', '따를 수 있다'], answer: 1 },
  { type: 'quiz', question: '"pabbajitena"의 -ena는?', options: ['주격 (~이/가)', '구격 (~에 의해)', '처격 (~에서)', '호격 (~이여)'], answer: 1 },
  { type: 'writing', instruction: '"비구들이여"를 써보세요 (호격)', meaning: '비구들이여', pronKo: '빅카웨', answer: 'bhikkhave' },
  { type: 'writing', instruction: '"극단들"을 써보세요', meaning: '극단들 (주격 복수)', pronKo: '안따~', answer: 'antā' },

  // ===== 4문장: 중도 (주요 단어) =====
  { type: 'teach', icon: '⚖️', word: 'majjhimā', pronKo: '맛지마~', meaning: '중간의, 중도의',
    grammar: '형용사, 주격 여성 단수', baseForm: 'majjhima (중간의)',
    formNote: 'majjhima → majjhimā: 여성 주격 -ā',
    buddhism: '중도(中道). 쾌락과 고행의 양극단을 피하는 길.', verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🛤️', word: 'paṭipadā', pronKo: '빠띠빠다~', meaning: '도, 길, 수행법',
    grammar: '여성명사, 주격 단수', baseForm: 'paṭipadā (수행의 길)',
    formNote: 'paṭi(향하여) + pada(걸음) = 수행의 길\n여성명사이므로 형용사 majjhimā도 여성형',
    buddhism: '도(道). 사성제의 넷째(도성제)와 연결.', verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '🙏', word: 'tathāgatena', pronKo: '따타~가떼나', meaning: '여래에 의해',
    grammar: '남성명사, 구격 단수', baseForm: 'tathāgata (여래)',
    formNote: 'tathāgata → tathāgatena: -a 어간 구격 -ena\ntathā(그렇게) + gata(간) = "그렇게 간 자"',
    buddhism: '여래(如來). 붓다의 자칭. "진리에 따라 온/간 자".', verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'teach', icon: '💡', word: 'abhisambuddhā', pronKo: '아비삼붓다~', meaning: '완전히 깨달은',
    grammar: '과거분사, 주격 여성 단수', baseForm: 'abhisambujjhati (완전히 깨닫다)',
    formNote: 'abhi(완전히) + sam(함께) + √budh(깨닫다)\n과거분사 = "~된" (영어 -ed)\npaṭipadā(여성)을 수식하므로 여성형 -ā',
    buddhism: '정등각(正等覺). 완전한 깨달음. √budh = Buddha의 어근!', verseLine: V4, verseLineKo: V4K, audio: true },
  { type: 'verse', pali: V4, pronKo: '에떼 코, 빅카웨, 우보 안떼 아누빠감마 맛지마~ 빠띠빠다~ 따타~가떼나 아비삼붓다~',
    translation: V4K, highlight: ['majjhimā','paṭipadā','tathāgatena','abhisambuddhā'],
    note: '☸️ 중도! 붓다의 핵심 방법론. abhisambuddhā의 어근 √budh = Buddha!' },
  { type: 'quiz', question: '중도(majjhimā paṭipadā)란?', options: ['쾌락에 빠지는 것', '고행으로 괴롭히는 것', '양극단을 피하는 길', '아무것도 안 하는 것'], answer: 2 },

  // ===== 5문장: 팔정도 (핵심 단어) =====
  { type: 'teach', icon: '☸️', word: 'ariyo', pronKo: '아리요', meaning: '성스러운, 고귀한',
    grammar: '형용사, 주격 남성 단수', baseForm: 'ariya (성스러운)',
    formNote: 'ariya → ariyo: -a 어간 남성 주격 -o',
    buddhism: '성(聖). 깨달음에 이르는. "아리야"는 수행자를 가리키기도 함.', verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '8️⃣', word: 'aṭṭhaṅgiko', pronKo: '앗탕기꼬', meaning: '여덟 가지의',
    grammar: '형용사, 주격 남성 단수', baseForm: 'aṭṭhaṅgika',
    formNote: 'aṭṭha(8) + aṅga(요소) + ika(형용사 접미사)\n합성어: "여덟 요소를 가진"', verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '🛤️', word: 'maggo', pronKo: '막고', meaning: '도, 길',
    grammar: '남성명사, 주격 단수', baseForm: 'magga (길)',
    formNote: 'magga → maggo: -a 어간 남성 주격 -o\n"ariyo aṭṭhaṅgiko maggo" = 성스러운 여덟 요소의 길',
    buddhism: '도(道). 사성제 넷째. 괴로움 소멸로 이끄는 길.', verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '👁️', word: 'sammādiṭṭhi', pronKo: '삼마~딧티', meaning: '바른 견해',
    grammar: '여성명사, 주격', baseForm: 'sammā(바른) + diṭṭhi(견해)',
    formNote: 'sammā = 바른, 올바른 (부사/접두사)\ndiṭṭhi = 견해, 봄 (√dis에서)',
    buddhism: '정견(正見). 팔정도 첫째. 사성제를 바로 아는 것.', verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'teach', icon: '🧘', word: 'sammāsati', pronKo: '삼마~사띠', meaning: '바른 마음챙김',
    grammar: '여성명사, 주격', baseForm: 'sammā(바른) + sati(마음챙김)',
    formNote: 'sati = 알아차림, 기억 (√sar에서)\n이것이 사념처경(MN 10)의 주제!',
    buddhism: '정념(正念). 팔정도 일곱째. 사념처 수행. 🎯 우리 학습의 최종 목표!', verseLine: V5, verseLineKo: V5K, audio: true },
  { type: 'verse', pali: V5, pronKo: '아야메와 아리요 앗탕기꼬 막고—삼마~딧티 ... 삼마~사띠 삼마~사마~디.',
    translation: V5K, highlight: ['ariyo','maggo','sammādiṭṭhi','sammāsati','sammāsamādhi'],
    note: '☸️ 팔정도! sammāsati(바른 마음챙김) = 사념처 수행 = 우리 최종 목표!' },
  { type: 'quiz', question: '"sammāsati"의 뜻은?', options: ['바른 견해', '바른 말', '바른 마음챙김', '바른 삼매'], answer: 2 },
  { type: 'writing', instruction: '"중도"를 빠알리어로 써보세요', meaning: '중도 (중간의 길)', pronKo: '맛지마~ 빠띠빠다~', answer: 'majjhimā paṭipadā' },
  { type: 'writing', instruction: '"성스러운 팔정도"를 써보세요', meaning: '성스러운 여덟 가지 길', pronKo: '아리요 앗탕기꼬 막고', answer: 'ariyo aṭṭhaṅgiko maggo' },
  { type: 'writing', instruction: '"바른 마음챙김"을 써보세요', meaning: '바른 마음챙김 (정념)', pronKo: '삼마~사띠', answer: 'sammāsati' },
  { type: 'speak', pali: 'sammādiṭṭhi sammāsaṅkappo sammāvācā sammākammanto sammāājīvo sammāvāyāmo sammāsati sammāsamādhi',
    pronKo: '삼마~딧티 삼마~상깝뽀 삼마~와~짜~ 삼마~깜만또 삼마~아~지~워 삼마~와~야~모 삼마~사띠 삼마~사마~디' },

  // ===== 6-7문장: 고성제 =====
  { type: 'teach', icon: '📜', word: 'dukkhaṃ', pronKo: '둑캉', meaning: '괴로움',
    grammar: '중성명사, 주격 단수', baseForm: 'dukkha (괴로움)',
    formNote: 'dukkha → dukkhaṃ: 중성 -a 어간 주격 -ṃ\n💡 남성 주격은 -o인데 중성 주격은 -ṃ!',
    buddhism: '고(苦). 사성제 첫째. 단순 고통이 아닌 불만족·불완전함 포괄.', verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '📜', word: 'ariyasaccaṃ', pronKo: '아리야삿짱', meaning: '성스러운 진리',
    grammar: '중성명사, 주격 단수', baseForm: 'ariyasacca',
    formNote: 'ariya(성스러운) + sacca(진리) + ṃ(중성 주격)\n합성어: "성스러운 진리"',
    buddhism: '성제(聖諦). 사성제의 각 항목.', verseLine: V6, verseLineKo: V6K, audio: true },
  { type: 'teach', icon: '👶', word: 'jātipi', pronKo: '자~띠삐', meaning: '태어남도',
    grammar: 'jāti(여성명사) + pi(불변어 "~도")', baseForm: 'jāti (탄생)',
    formNote: 'jāti + pi(~도) = 태어남도\npi = 영어 also. 모든 항목 뒤에 붙어 강조',
    buddhism: '생(生). 윤회에서의 태어남. 12연기의 11번째.', verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '👴', word: 'jarāpi', pronKo: '자라~삐', meaning: '늙음도',
    grammar: 'jarā(여성명사) + pi', baseForm: 'jarā (늙음)',
    formNote: 'jarā + pi = 늙음도', buddhism: '노(老). 늙음, 쇠퇴.', verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '🤒', word: 'byādhipi', pronKo: '뱌~디삐', meaning: '병듦도',
    grammar: 'byādhi(남성명사) + pi', baseForm: 'byādhi (병)',
    formNote: 'byādhi + pi = 병듦도\n💡 byādhi는 남성이라 "dukkho"(남성 주격)', buddhism: '병(病).', verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'teach', icon: '💀', word: 'maraṇampi', pronKo: '마라낭삐', meaning: '죽음도',
    grammar: 'maraṇa(중성명사) + m + pi', baseForm: 'maraṇa (죽음)',
    formNote: 'maraṇa + ṃ(연음) + pi = 죽음도\n√mar(죽다)에서 유래', buddhism: '사(死). 12연기 마지막.', verseLine: V7, verseLineKo: V7K, audio: true },
  { type: 'verse', pali: `${V6}\n${V7}`, pronKo: '이당 코 빠나, 빅카웨, 둑캉 아리야삿짱—\n자~띠삐 둑카~, 자라~삐 둑카~, 뱌~디삐 둑코, 마라낭삐 둑캉',
    translation: `${V6K}\n${V7K}`, highlight: ['dukkhaṃ','ariyasaccaṃ','jātipi','jarāpi','byādhipi','maraṇampi'],
    note: '☸️ 고성제: 생로병사(生老病死) = 붓다가 출가를 결심한 네 가지 고통!' },
  { type: 'quiz', question: '사성제 첫째 "고성제"의 핵심은?', options: ['행복이 최고', '생로병사가 모두 괴로움', '신을 믿어야', '고행이 답'], answer: 1 },
  { type: 'quiz', question: '"pi"의 뜻은?', options: ['~이다', '~않다', '~도 (also)', '~을/를'], answer: 2 },
  { type: 'writing', instruction: '"괴로움"을 써보세요', meaning: '괴로움 (고)', pronKo: '둑캉', answer: 'dukkhaṃ' },
  { type: 'writing', instruction: '"성스러운 진리"를 써보세요', meaning: '성제', pronKo: '아리야삿짱', answer: 'ariyasaccaṃ' },
  { type: 'arrange', instruction: '문장을 배열하세요', translation: '한 때 세존께서 바라나시에 머무셨다',
    blocks: ['viharati', 'bhagavā', 'ekaṃ', 'samayaṃ', 'bārāṇasiyaṃ'], correctOrder: [2, 3, 1, 4, 0] },

  // ===== 두 극단 정의 =====
  { type: 'intro', icon: '⚖️', title: '— 두 극단 (dveme antā) —', subtitle: '쾌락주의 vs 고행주의',
    description: '출가자가 따르지 말아야 할 두 극단.' },
  { type: 'teach', icon: '💋', word: 'kāmasukhallikānuyogo', pronKo: '까~마수칼리까~누요고', meaning: '감각적 쾌락에 빠지는 것',
    grammar: '복합어, 주격', baseForm: 'kāma(욕망) + sukha(즐거움) + allika(집착) + anuyoga(전념)',
    buddhism: '쾌락주의(快樂主義). 부처님 출가 전 왕자 시절 6년간 향유한 극단.',
    audio: true },
  { type: 'teach', icon: '🔥', word: 'attakilamathānuyogo', pronKo: '앗따낄라마타~누요고', meaning: '자기 학대에 빠지는 것 (고행)',
    grammar: '복합어, 주격', baseForm: 'atta(자기) + kilamatha(괴롭힘) + anuyoga',
    buddhism: '고행주의(苦行主義). 부처님 깨달음 전 6년 단식 등의 극단.',
    audio: true },
  { type: 'teach', icon: '🙅', word: 'hīno gammo pothujjaniko anariyo anatthasaṃhito', pronKo: '히~노 감모 뽀툿자니꼬 아나리요 아낫타상히또', meaning: '천박·속된·범부의·비성스러운·무익한',
    grammar: '형용사 5개 주격', baseForm: 'hīna+gamma+pothujjanika+anariya+anatthasaṃhita',
    formNote: '쾌락주의의 5가지 부정적 형용',
    audio: true },
  { type: 'verse', pali: '"yo cāyaṃ kāmesu kāmasukhallikānuyogo hīno gammo pothujjaniko anariyo anatthasaṃhito, yo cāyaṃ attakilamathānuyogo dukkho anariyo anatthasaṃhito."',
    pronKo: '요 짜~양 까~메수 까~마수칼리까~누요고 히~노 감모 뽀툿자니꼬 아나리요 아낫타상히또, 요 짜~양 앗따낄라마타~누요고 둑코 아나리요 아낫타상히또.',
    translation: '"하나는 감각적 쾌락에 빠지는 것이니 — 천박하고 속되고 범부의 것이며 비성스럽고 무익하다. 또 하나는 자기 학대(고행)에 빠지는 것이니 — 괴롭고 비성스럽고 무익하다."',
    highlight: ['kāmasukhallikānuyogo','attakilamathānuyogo','hīno','gammo','pothujjaniko','anariyo','anatthasaṃhito'],
    note: '⚖️ 두 극단 정의 — 부처님이 직접 경험으로 거부.' },

  // ===== 중도의 5공덕 =====
  { type: 'intro', icon: '🛤️', title: '— 중도의 5가지 공덕 —', subtitle: 'cakkhukaraṇī ñāṇakaraṇī...',
    description: '중도는 ① 눈을 만들고 ② 앎을 만들며 ③ 평온·④ 신통·⑤ 깨달음·열반으로 이끈다.' },
  { type: 'teach', icon: '👁️', word: 'cakkhukaraṇī', pronKo: '짝쿠까라니~', meaning: '눈을 만드는',
    grammar: '복합어, 주격 여성', baseForm: 'cakkhu + karaṇī (만드는)',
    formNote: 'paṭipadā(여성)를 수식 → -ī',
    audio: true },
  { type: 'teach', icon: '🧠', word: 'ñāṇakaraṇī', pronKo: '냐~나까라니~', meaning: '앎을 만드는',
    grammar: '복합어, 주격 여성', baseForm: 'ñāṇa + karaṇī',
    audio: true },
  { type: 'teach', icon: '☮️', word: 'upasamāya', pronKo: '우빠사마~야', meaning: '평온을 위해',
    grammar: '남성명사, 여격', baseForm: 'upasama (평온)',
    audio: true },
  { type: 'teach', icon: '✨', word: 'abhiññāya', pronKo: '아빈냐~야', meaning: '신통(승지)을 위해',
    grammar: '여성명사, 여격', baseForm: 'abhiññā (직관/신통)',
    audio: true },
  { type: 'teach', icon: '💡', word: 'sambodhāya', pronKo: '삼보다~야', meaning: '깨달음을 위해',
    grammar: '남성명사, 여격', baseForm: 'sambodha (깨달음)',
    audio: true },
  { type: 'teach', icon: '🕊️', word: 'nibbānāya', pronKo: '닙바~나~야', meaning: '열반을 위해',
    grammar: '중성명사, 여격', baseForm: 'nibbāna',
    audio: true },
  { type: 'teach', icon: '🛤️', word: 'saṃvattati', pronKo: '상왓따띠', meaning: '이끈다, 향한다',
    grammar: '동사 3인칭 단수 현재', baseForm: 'saṃvattati (saṃ + √vatt)',
    audio: true },
  { type: 'verse', pali: '"...majjhimā paṭipadā tathāgatena abhisambuddhā cakkhukaraṇī ñāṇakaraṇī upasamāya abhiññāya sambodhāya nibbānāya saṃvattati."',
    pronKo: '맛지마~ 빠띠빠다~ 따타~가떼나 아비삼붓다~ 짝쿠까라니~ 냐~나까라니~ 우빠사마~야 아빈냐~야 삼보다~야 닙바~나~야 상왓따띠.',
    translation: '"여래가 깨달은 중도는 눈을 만들고 앎을 만들며, 평온과 신통과 깨달음과 열반으로 이끈다."',
    highlight: ['cakkhukaraṇī','ñāṇakaraṇī','upasamāya','abhiññāya','sambodhāya','nibbānāya','saṃvattati'],
    note: '🛤️ 중도가 인도하는 5단계: 눈·앎·평온·신통·깨달음/열반.' },

  // ===== 집성제 =====
  { type: 'intro', icon: '🔥', title: '— 집성제 (dukkhasamudaya) —', subtitle: '갈애 — 욕애·유애·무유애',
    description: '괴로움의 원인 = 3가지 갈애.' },
  { type: 'teach', icon: '🔥', word: 'taṇhā', pronKo: '딴하~', meaning: '갈애',
    grammar: '여성명사, 주격 단수', baseForm: 'taṇhā',
    formNote: '11과 MN10 V_SAM_S0과 동일',
    buddhism: '애(愛). 4성제 집성제 = taṇhā.',
    audio: true },
  { type: 'teach', icon: '🔄', word: 'ponobbhavikā', pronKo: '뽀높바위까~', meaning: '다시 존재로 이끄는',
    grammar: '형용사, 주격 여성', baseForm: 'puna + bhava + -ika',
    audio: true },
  { type: 'teach', icon: '😍', word: 'nandirāgasahagatā', pronKo: '난디라~가사하가따~', meaning: '즐김과 탐욕 동반',
    grammar: '복합어, 주격 여성', baseForm: 'nandi(즐김) + rāga + sahagata',
    audio: true },
  { type: 'teach', icon: '💋', word: 'kāmataṇhā', pronKo: '까~마딴하~', meaning: '욕애',
    grammar: '복합어, 주격', baseForm: 'kāma + taṇhā',
    buddhism: '욕애(欲愛). 3갈애 첫째.',
    audio: true },
  { type: 'teach', icon: '♾️', word: 'bhavataṇhā', pronKo: '바와딴하~', meaning: '유애 (존재의 갈애)',
    grammar: '복합어, 주격', baseForm: 'bhava + taṇhā',
    buddhism: '유애(有愛).',
    audio: true },
  { type: 'teach', icon: '🗑️', word: 'vibhavataṇhā', pronKo: '위바와딴하~', meaning: '무유애 (비존재의 갈애)',
    grammar: '복합어, 주격', baseForm: 'vibhava + taṇhā',
    buddhism: '무유애(無有愛).',
    audio: true },
  { type: 'verse', pali: '"idaṃ kho pana, bhikkhave, dukkhasamudayaṃ ariyasaccaṃ — yāyaṃ taṇhā ponobbhavikā nandirāgasahagatā tatratatrābhinandinī, seyyathidaṃ — kāmataṇhā, bhavataṇhā, vibhavataṇhā."',
    pronKo: '이당 코 빠나, 빅카웨, 둑카사무다양 아리야삿짱 — 야~양 딴하~ 뽀높바위까~ 난디라~가사하가따~ 따뜨라따뜨라~비난디니~, 셋야티당 — 까~마딴하~, 바와딴하~, 위바와딴하~.',
    translation: '"비구들이여, 이것이 괴로움의 일어남의 성스러운 진리이다 — 다시 존재로 이끌고 즐김과 탐욕을 동반하며 여기저기서 즐기는 갈애 — 곧 욕애·유애·무유애이다."',
    highlight: ['taṇhā','ponobbhavikā','kāmataṇhā','bhavataṇhā','vibhavataṇhā'],
    note: '🔥 집성제 = 3갈애.' },

  // ===== 멸성제 =====
  { type: 'intro', icon: '🕊️', title: '— 멸성제 (dukkhanirodha) —', subtitle: '갈애의 남김 없는 사라짐 = 열반',
    description: '갈애의 완전한 소멸이 곧 열반.' },
  { type: 'teach', icon: '🌬️', word: 'asesavirāganirodho', pronKo: '아세사위라~가니로도', meaning: '남김 없는 빛바램·사라짐',
    grammar: '복합어, 주격', baseForm: 'asesa + virāga + nirodha',
    formNote: '11과 MN10 V_NIR0과 동일',
    audio: true },
  { type: 'teach', icon: '🎁', word: 'cāgo', pronKo: '짜~고', meaning: '버림',
    grammar: '남성명사, 주격', baseForm: 'cāga',
    audio: true },
  { type: 'teach', icon: '🕊️', word: 'paṭinissaggo', pronKo: '빠띠닛삭고', meaning: '놓아 버림',
    grammar: '남성명사, 주격', baseForm: 'paṭinissagga',
    audio: true },
  { type: 'teach', icon: '🆓', word: 'mutti', pronKo: '뭇띠', meaning: '벗어남, 해탈',
    grammar: '여성명사, 주격', baseForm: 'mutti',
    audio: true },
  { type: 'teach', icon: '✨', word: 'anālayo', pronKo: '아날~라요', meaning: '집착 없음',
    grammar: '남성명사, 주격', baseForm: 'an + ālaya',
    audio: true },
  { type: 'verse', pali: '"idaṃ kho pana, bhikkhave, dukkhanirodhaṃ ariyasaccaṃ — yo tassāyeva taṇhāya asesavirāganirodho cāgo paṭinissaggo mutti anālayo."',
    pronKo: '이당 코 빠나, 빅카웨, 둑카니로당 아리야삿짱 — 요 땃사~예와 딴하~야 아세사위라~가니로도 짜~고 빠띠닛삭고 뭇띠 아날~라요.',
    translation: '"비구들이여, 이것이 괴로움의 소멸의 성스러운 진리이다 — 바로 그 갈애의 남김 없는 빛바램과 사라짐, 버림, 놓아버림, 벗어남, 집착 없음."',
    highlight: ['asesavirāganirodho','cāgo','paṭinissaggo','mutti','anālayo'],
    note: '🕊️ 멸성제 = 열반.' },

  // ===== 도성제 (팔정도 다시) =====
  { type: 'verse', pali: '"idaṃ kho pana, bhikkhave, dukkhanirodhagāminī paṭipadā ariyasaccaṃ — ayameva ariyo aṭṭhaṅgiko maggo, seyyathidaṃ — sammādiṭṭhi ... sammāsamādhi."',
    pronKo: '이당 코 빠나, 빅카웨, 둑카니로다가~미니~ 빠띠빠다~ 아리야삿짱 — 아야메와 아리요 앗탕기꼬 막고, 셋야티당 — 삼마~딧티 ... 삼마~사마~디.',
    translation: '"비구들이여, 이것이 괴로움의 소멸로 이끄는 길의 성스러운 진리이다 — 바로 성스러운 팔정도이니 — 정견 ... 정정이다."',
    note: '☸️ 도성제 = 팔정도. (5과 sn45-8에서 상세).' },

  // ===== 3전 12행 =====
  { type: 'intro', icon: '🔄', title: '— 3전 12행 (tiparivaṭṭa dvādasākāra) —', subtitle: '사성제 각각 3측면',
    description: '각 성제마다:\n① 시전(示轉) — 이것이 X이다\n② 권전(勸轉) — 이것을 X해야 한다\n③ 증전(證轉) — 이것을 X했다\n4성제 × 3 = 12행.' },
  { type: 'teach', icon: '👁️', word: 'cakkhuṃ udapādi', pronKo: '짝쿵 우다빠~디', meaning: '눈이 생겨났다',
    grammar: '중성명사 주격 + 동사 아오리스트', baseForm: 'cakkhu(눈) + udapādi(생겨남)',
    formNote: '깨달음의 다섯 비유 (cakkhuṃ·ñāṇaṃ·paññā·vijjā·āloko)의 첫째',
    audio: true },
  { type: 'teach', icon: '🧠', word: 'ñāṇaṃ udapādi', pronKo: '냐~낭 우다빠~디', meaning: '앎이 생겨났다',
    grammar: '주격+아오리스트', baseForm: 'ñāṇa + udapādi',
    audio: true },
  { type: 'teach', icon: '💎', word: 'paññā udapādi', pronKo: '빤냐~ 우다빠~디', meaning: '지혜가 생겨났다',
    grammar: '주격+아오리스트', baseForm: 'paññā + udapādi',
    audio: true },
  { type: 'teach', icon: '🎓', word: 'vijjā udapādi', pronKo: '윗자~ 우다빠~디', meaning: '명지가 생겨났다',
    grammar: '주격+아오리스트', baseForm: 'vijjā + udapādi',
    audio: true },
  { type: 'teach', icon: '💡', word: 'āloko udapādi', pronKo: '아~로꼬 우다빠~디', meaning: '광명이 생겨났다',
    grammar: '주격+아오리스트', baseForm: 'āloka + udapādi',
    audio: true },
  { type: 'teach', icon: '🔍', word: 'pariññeyyaṃ / pariññātaṃ', pronKo: '빠린녜이양 / 빠린냐~땅', meaning: '두루 알아야 할 / 두루 알았다',
    grammar: '미래분사 / 과거분사', baseForm: 'pariññā (두루 앎)',
    buddhism: '고성제의 권전·증전 동사. 고는 알아야 한다.',
    audio: true },
  { type: 'teach', icon: '🧹', word: 'pahātabbaṃ / pahīnaṃ', pronKo: '빠하~땁방 / 빠히~낭', meaning: '버려야 할 / 버려졌다',
    grammar: '미래분사 / 과거분사', baseForm: 'pahāna',
    buddhism: '집성제의 권전·증전. 집은 버려야 한다.',
    audio: true },
  { type: 'teach', icon: '👁️', word: 'sacchikātabbaṃ / sacchikataṃ', pronKo: '삿치까~땁방 / 삿치까땅', meaning: '실현해야 할 / 실현했다',
    grammar: '미래분사 / 과거분사', baseForm: 'sacchikiriyā',
    buddhism: '멸성제의 권전·증전. 멸은 실현해야 한다.',
    audio: true },
  { type: 'teach', icon: '🌱', word: 'bhāvetabbaṃ / bhāvitaṃ', pronKo: '바~웨땁방 / 바~위땅', meaning: '닦아야 할 / 닦았다',
    grammar: '미래분사 / 과거분사', baseForm: 'bhāvanā',
    buddhism: '도성제의 권전·증전. 도는 닦아야 한다.',
    audio: true },
  { type: 'verse', pali: '"\'idaṃ dukkhaṃ ariyasaccan\'ti me, bhikkhave, pubbe ananussutesu dhammesu cakkhuṃ udapādi, ñāṇaṃ udapādi, paññā udapādi, vijjā udapādi, āloko udapādi."',
    pronKo: '이당 둑캉 아리야삿짠띠 메, 빅카웨, 뿝베 아나눗수떼수 담메수 짝쿵 우다빠~디, 냐~낭 우다빠~디, 빤냐~ 우다빠~디, 윗자~ 우다빠~디, 아~로꼬 우다빠~디.',
    translation: '"\'이것이 괴로움의 성스러운 진리이다\'라는 — 비구들이여, 이전에 듣지 못한 법들에 대해 나에게 눈이 생겨났고, 앎이 생겨났고, 지혜가 생겨났고, 명지가 생겨났고, 광명이 생겨났다."',
    highlight: ['cakkhuṃ','ñāṇaṃ','paññā','vijjā','āloko','udapādi'],
    note: '🔄 시전(示轉) — 12행 중 첫 행: "이것이 고이다".' },

  // ===== 깨달음 선언 =====
  { type: 'intro', icon: '🏆', title: '— 깨달음 선언 —', subtitle: 'anuttaraṃ sammāsambodhiṃ abhisambuddho',
    description: '3전12행이 청정해진 후 비로소 무상정등각 선언.' },
  { type: 'teach', icon: '🔄', word: 'tiparivaṭṭaṃ dvādasākāraṃ', pronKo: '띠빠리왓땅 드와~다사~까~랑', meaning: '3전 12행',
    grammar: '복합어', baseForm: 'ti(3) + parivaṭṭa(굴림) + dvādasa(12) + ākāra(모양)',
    buddhism: '3전12행상(三轉十二行相).',
    audio: true },
  { type: 'teach', icon: '✨', word: 'yathābhūtaṃ ñāṇadassanaṃ', pronKo: '야타~부~땅 냐~나닷사낭', meaning: '있는 그대로의 지혜와 봄',
    grammar: '부사+복합어', baseForm: 'yathābhūta + ñāṇa + dassana',
    audio: true },
  { type: 'teach', icon: '👑', word: 'anuttaraṃ sammāsambodhiṃ', pronKo: '아눗따랑 삼마~삼보딩', meaning: '무상정등각',
    grammar: '형용사+명사 대격', baseForm: 'anuttara + sammāsambodhi',
    buddhism: '무상정등각(無上正等覺). 최고의 완전한 깨달음.',
    audio: true },
  { type: 'teach', icon: '🏆', word: 'abhisambuddho', pronKo: '아비삼붓도', meaning: '완전히 깨달은 (주격)',
    grammar: '과거분사, 주격 남성', baseForm: 'abhisambuddha',
    audio: true },
  { type: 'teach', icon: '📢', word: 'paccaññāsiṃ', pronKo: '빳짠냐~싱', meaning: '선언했다 (1인칭 단수 아오리스트)',
    grammar: '동사 1인칭 단수 아오리스트', baseForm: 'paṭi + √ñā',
    audio: true },
  { type: 'verse', pali: '"yato ca kho me, bhikkhave, imesu catūsu ariyasaccesu evaṃ tiparivaṭṭaṃ dvādasākāraṃ yathābhūtaṃ ñāṇadassanaṃ suvisuddhaṃ ahosi, athāhaṃ... \'anuttaraṃ sammāsambodhiṃ abhisambuddho\'ti paccaññāsiṃ."',
    pronKo: '야또 짜 코 메, 빅카웨, 이메수 짜뚜~수 아리야삿쩨수 에왕 띠빠리왓땅 드와~다사~까~랑 야타~부~땅 냐~나닷사낭 수위숫당 아호시, 아타~항... 아눗따랑 삼마~삼보딩 아비삼붓도띠 빳짠냐~싱.',
    translation: '"비구들이여, 4성제에 대해 3전12행의 있는 그대로의 지혜와 봄이 잘 청정해진 후에야, 비로소 나는 ... \'무상정등각을 깨달았다\'고 선언하였다."',
    highlight: ['tiparivaṭṭaṃ','dvādasākāraṃ','yathābhūtaṃ','ñāṇadassanaṃ','anuttaraṃ','sammāsambodhiṃ','abhisambuddho','paccaññāsiṃ'],
    note: '🏆 부처님의 깨달음 선언 — 4성제 3전12행 완성 후.' },

  // ===== 해탈지견 =====
  { type: 'teach', icon: '🔓', word: 'akuppā me vimutti', pronKo: '아꿉빠~ 메 위뭇띠', meaning: '나의 해탈은 흔들리지 않는다',
    grammar: '형용사+속격+주격', baseForm: 'akuppa(흔들리지 않는) + vimutti',
    buddhism: '부동(不動) 해탈. 아라한과의 표지.',
    audio: true },
  { type: 'teach', icon: '🏁', word: 'ayamantimā jāti', pronKo: '아야만띠마~ 자~띠', meaning: '이것이 마지막 생이다',
    grammar: '대명사+형용사+명사', baseForm: 'ayaṃ + antimā + jāti',
    audio: true },
  { type: 'teach', icon: '🚫', word: 'natthidāni punabbhavo', pronKo: '낫티다~니 뿌납바오', meaning: '이제 다시 태어남이 없다',
    grammar: 'natthi+idāni+punabbhava', baseForm: 'natthi(없다) + idāni(이제) + punabbhava(재생)',
    audio: true },
  { type: 'verse', pali: '"ñāṇañca pana me dassanaṃ udapādi — \'akuppā me vimutti, ayamantimā jāti, natthidāni punabbhavo\'ti."',
    pronKo: '냐~난짜 빠나 메 닷사낭 우다빠~디 — 아꿉빠~ 메 위뭇띠, 아야만띠마~ 자~띠, 낫티다~니 뿌납바오띠.',
    translation: '"그리고 나에게 지혜와 봄이 생겨났다 — \'나의 해탈은 흔들리지 않는다. 이것이 마지막 생이다. 이제 다시 태어남은 없다.\'"',
    highlight: ['akuppā','vimutti','antimā','jāti','natthidāni','punabbhavo'],
    note: '🔓 해탈지견 — 아라한과의 자증.' },

  // ===== 콘단냐의 법안 =====
  { type: 'intro', icon: '👁️', title: '— 콘단냐의 법안 —', subtitle: '예류과 증득',
    description: '설법 도중 콘단냐 존자가 첫 깨달음(예류과)을 얻음.' },
  { type: 'teach', icon: '🌱', word: 'virajaṃ vītamalaṃ dhammacakkhuṃ', pronKo: '위라장 위~따말랑 담마짝쿵', meaning: '티끌 없고 때 없는 법안',
    grammar: '형용사+형용사+복합어', baseForm: 'viraja + vītamala + dhammacakkhu',
    buddhism: '법안(法眼). 예류과의 표지.',
    audio: true },
  { type: 'teach', icon: '💡', word: 'yaṃ kiñci samudayadhammaṃ sabbaṃ taṃ nirodhadhammaṃ', pronKo: '양 낀찌 사무다야담망 삽방 땅 니로다담망', meaning: '일어남의 법성인 것은 모두 사라짐의 법성이다',
    grammar: '관계절', baseForm: 'samudaya + dhamma + nirodha + dhamma',
    formNote: '예류과 깨달음의 정형구',
    buddhism: '모든 조건지어진 것은 무상하다. 깨달음의 첫 통찰.',
    audio: true },
  { type: 'verse', pali: '"imasmiñca pana veyyākaraṇasmiṃ bhaññamāne āyasmato Koṇḍaññassa virajaṃ vītamalaṃ dhammacakkhuṃ udapādi — \'yaṃ kiñci samudayadhammaṃ, sabbaṃ taṃ nirodhadhamman\'ti."',
    pronKo: '이마스민짜 빠나 웨이야~까라낫밍 반냐마~네 아~야스마또 꼰단냣사 위라장 위~따말랑 담마짝쿵 우다빠~디 — 양 낀찌 사무다야담망, 삽방 땅 니로다담만띠.',
    translation: '"이 설명이 설해질 때 콘단냐 존자에게 티끌 없고 때 없는 법안이 생겨났다 — \'일어남의 법성인 것은 모두 사라짐의 법성이다.\'"',
    highlight: ['virajaṃ','vītamalaṃ','dhammacakkhuṃ','samudayadhammaṃ','nirodhadhammaṃ'],
    note: '👁️ 콘단냐의 예류과 — 불교 최초의 제자 깨달음.' },

  // ===== 천신들의 환호 =====
  { type: 'intro', icon: '🌟', title: '— 천신들의 환호 —', subtitle: '6천의 법륜 굴림 알림',
    description: '지신→사대왕천→33천→야마천→도솔천→화락천→타화자재천→범천까지 법륜 굴림이 알려짐.' },
  { type: 'teach', icon: '🌍', word: 'bhummā devā saddamanussāvesuṃ', pronKo: '붐마~ 데와~ 삿다마눗사~웨숭', meaning: '지신들이 소리쳤다',
    grammar: '주격복수+동사아오리스트', baseForm: 'bhumma + deva + saddamanussāveti',
    audio: true },
  { type: 'teach', icon: '☸️', word: 'anuttaraṃ dhammacakkaṃ pavattitaṃ', pronKo: '아눗따랑 담마짝깡 빠왓띠땅', meaning: '위 없는 법륜이 굴려졌다',
    grammar: '형용사+명사+과거분사 대격', baseForm: 'anuttara + dhammacakka + pavattita',
    buddhism: '전법륜(轉法輪). 경의 제목 자체.',
    audio: true },
  { type: 'teach', icon: '🛡️', word: 'appaṭivattiyaṃ', pronKo: '압빠띠왓띠양', meaning: '되돌릴 수 없는',
    grammar: '형용사, 대격', baseForm: 'a + paṭivattiya',
    audio: true },
  { type: 'verse', pali: '"pavattite ca pana bhagavatā dhammacakke bhummā devā saddamanussāvesuṃ — \'etaṃ bhagavatā bārāṇasiyaṃ isipatane migadāye anuttaraṃ dhammacakkaṃ pavattitaṃ appaṭivattiyaṃ samaṇena vā brāhmaṇena vā devena vā mārena vā brahmunā vā kenaci vā lokasmin\'ti."',
    pronKo: '빠왓띠떼 짜 빠나 바가와따~ 담마짝께 붐마~ 데와~ 삿다마눗사~웨숭 — 에땅 바가와따~ 바~라~나시양 이시빠따네 미가다~예 아눗따랑 담마짝깡 빠왓띠땅 압빠띠왓띠양 사마네나 와~ 브라~흐마네나 와~ 데웨나 와~ 마~레나 와~ 브라흐무나~ 와~ 께나찌 와~ 로까스민띠.',
    translation: '"세존께서 법륜을 굴리시자 지신들이 소리쳤다 — \'세존께서 바라나시 이시빠따나 녹야원에서 위 없는 법륜을 굴리셨다. 어떤 사문·바라문·신·마라·범천·세상의 누구도 되돌릴 수 없다.\'"',
    highlight: ['bhummā','devā','saddamanussāvesuṃ','dhammacakkaṃ','pavattitaṃ','appaṭivattiyaṃ'],
    note: '🌟 지신들의 첫 환호 — 이후 사대왕천·33천·야마·도솔·화락·타화자재·범천까지 차례로 전해짐.' },

  // ===== 아냐타꼰단냐 =====
  { type: 'verse', pali: '"atha kho bhagavā imaṃ udānaṃ udānesi — \'aññāsi vata, bho, Koṇḍañño, aññāsi vata, bho, Koṇḍañño\'ti! iti hidaṃ āyasmato Koṇḍaññassa \'Aññāsikoṇḍañño\' tveva nāmaṃ ahosīti."',
    pronKo: '아타 코 바가와~ 이망 우다~낭 우다~네시 — 안냐~시 와따, 보, 꼰단뇨, 안냐~시 와따, 보, 꼰단뇨띠! 이띠 히당 아~야스마또 꼰단냣사 안냐~시꼰단뇨 뜨웨와 나~망 아호시~띠.',
    translation: '"그러자 세존께서 감흥어를 읊으셨다 — \'아, 콘단냐가 알았구나! 아, 콘단냐가 알았구나!\' 이렇게 해서 콘단냐 존자에게는 \'안냐꼰단냐(알았다 꼰단냐)\'라는 이름이 생겼다."',
    highlight: ['aññāsi','vata','bho','Koṇḍañño','Aññāsikoṇḍañño'],
    note: '🎉 경 결말 — 콘단냐가 안냐꼰단냐(알았다 꼰단냐)가 됨.' },

  // ===== 종합 퀴즈 =====
  { type: 'quiz', question: '전법륜경 첫 설법 장소는?', options: ['보드가야', '사위성', '바라나시 녹야원', '라자가하'], answer: 2 },
  { type: 'quiz', question: '"bhagavā"의 원형은?', options: ['bhagava', 'bhagavant', 'bhagavā', 'bhagavati'], answer: 1, hint: '-ant 어간 특수 주격형' },
  { type: 'quiz', question: '중도(majjhimā paṭipadā)의 구체적 내용은?', options: ['사성제', '팔정도', '오온', '십이연기'], answer: 1 },
  { type: 'quiz', question: '"abhisambuddhā"의 어근 √budh는 무슨 뜻?', options: ['가다', '보다', '깨닫다', '말하다'], answer: 2, hint: 'Buddha의 어근!' },
  { type: 'quiz', question: '두 극단(antā)은?', options: ['쾌락(kāmasukha) vs 고행(attakilamatha)', '신·구·의', '계·정·혜', '과거·미래'], answer: 0 },
  { type: 'quiz', question: '3전12행(tiparivaṭṭa dvādasākāra)이란?',
    options: ['4성제 × 3측면(시·권·증)', '12연기', '37조도품', '오온 분석'], answer: 0 },
  { type: 'quiz', question: '콘단냐가 첫 깨달음에서 본 진리는?',
    options: ['"일어남의 법성인 것은 모두 사라짐의 법성이다"', '"모든 것은 영원하다"', '"신이 모든 것을 창조했다"', '"무아는 거짓이다"'], answer: 0 },
  { type: 'quiz', question: '아냐타꼰단냐의 새 이름 "Aññāsikoṇḍañño"의 뜻은?',
    options: ['알았다 꼰단냐', '잠든 꼰단냐', '늙은 꼰단냐', '큰 꼰단냐'], answer: 0,
    hint: 'aññāsi = 알았다 (√ñā 아오리스트)' },
]
